// <auto-generated> Tools/VehicleNetCaches/gen_vehicle_caches.py - do not edit by hand.
//
// Each vehicle Blueprint's OWN replicated fields - properties and RPCs together, which is how
// UClass::SetUpRuntimeReplicationData builds NetFields (one list, sorted by name).
//
// A vehicle whose Blueprint adds nothing is ABSENT rather than listed empty; the runtime side
// treats "not in the table" as "adds no fields", which is the same answer and one fewer entry.

namespace AFortOnlineBeacon.Net;

internal static partial class FortVehicleNetCaches {
    /// <summary>6 vehicle Blueprints that add fields of their own.</summary>
    private static readonly Dictionary<string, string[]> OwnFields =
        new(StringComparer.OrdinalIgnoreCase) {
            ["AntelopeVehicle_C"] = new[] { "ApplyImpulse", "AttachedPickups", "DoorMesh", "FortPickup", "HonkMulticast", "HonkToServer", "ImpactLocation", "ImpulseVector", "Update Damage State" },
            ["FerretVehicle_C"] = new[] { "AttachedPickups", "DoorMesh", "FortPickup", "ImpactLocation", "ImpulseVector", "Update Damage State" },
            ["GolfCartVehicleSK_C"] = new[] { "ApplyImpulse", "AttachedPickups", "DoorMesh", "FortPickup", "ImpactLocation", "ImpulseVector", "Update Damage State" },
            ["OctopusVehicle_C"] = new[] { "HitWithPickaxe" },
            ["PushCannon_C"] = new[] { "ApplyImpulse", "AttachedPickups", "DoorMesh", "FortPickup", "ImpulseVector", "PawnLaunchedCosmetics", "Update Damage State" },
            ["ShoppingCartVehicleSK_C"] = new[] { "ApplyImpulse", "AttachedPickups", "FortPickup", "ImpulseVector", "Update Damage State" },
        };
}
