// <auto-generated> Tools/PakReader `buildinghealth` - do not edit by hand.
//
// Fortnite 10.40's REAL per-class building health and build time, resolved through the chain the
// game itself uses at runtime:
//
//   building CDO's AttributeInitKeys[1]  ->  category + size, e.g. AthenaPlayerBuildingWood1 + Size9
//   -> Athena/Balance/DataTables/AthenaAttributesBuildingSection
//      row '<category>.<size>.FortHealthSet.MaxHealth' (and '<category>.FortBuildingActorSet.BuildTime')
//
// WHICH attribute table to use is named only in FortniteGame/Config/DefaultGame.ini under
// [/Script/GameplayAbilities.AbilitySystemGlobals] - no asset points at it, which is why this sat
// unresolved for so long. AttributeInitKeys has TWO entries; the second is the Athena one.
//
// Sanity check on the numbers: wood wall 150, stone wall 300, metal wall 500 - Battle Royale's
// well-known values, which is what says the chain was resolved correctly and not merely plausibly.

namespace AFortOnlineBeacon.Net.Actors;

internal static class FortBuildingAttributes {
    /// <summary>Class name (as it appears in the class path's last segment) -> (MaxHealth, BuildTime seconds).</summary>
    public static readonly Dictionary<string, (int MaxHealth, float BuildTime)> ByClass = new(StringComparer.OrdinalIgnoreCase) {
        ["PBWA_M1_ArchwayLargeSupport_C"] = (240, 25f),
        ["PBWA_M1_ArchwayLarge_C"] = (370, 25f),
        ["PBWA_M1_Archway_C"] = (460, 25f),
        ["PBWA_M1_BalconyD_C"] = (330, 25f),
        ["PBWA_M1_BalconyI_C"] = (370, 25f),
        ["PBWA_M1_BalconyO_C"] = (220, 25f),
        ["PBWA_M1_BalconyS_C"] = (330, 25f),
        ["PBWA_M1_Brace_C"] = (460, 25f),
        ["PBWA_M1_DoorC_C"] = (480, 25f),
        ["PBWA_M1_DoorS_C"] = (460, 25f),
        ["PBWA_M1_DoorSide_C"] = (480, 25f),
        ["PBWA_M1_Floor_C"] = (460, 25f),
        ["PBWA_M1_HalfWallDoorS_C"] = (350, 25f),
        ["PBWA_M1_HalfWallDoor_C"] = (350, 25f),
        ["PBWA_M1_HalfWallHalf_C"] = (330, 25f),
        ["PBWA_M1_HalfWall_C"] = (370, 25f),
        ["PBWA_M1_Pillar_C"] = (350, 25f),
        ["PBWA_M1_QuarterWallHalf_C"] = (220, 25f),
        ["PBWA_M1_QuarterWallS_C"] = (240, 25f),
        ["PBWA_M1_RoofC_C"] = (460, 25f),
        ["PBWA_M1_RoofD_C"] = (460, 25f),
        ["PBWA_M1_RoofI_C"] = (460, 25f),
        ["PBWA_M1_RoofO_C"] = (460, 25f),
        ["PBWA_M1_RoofS_C"] = (460, 25f),
        ["PBWA_M1_RoofWall_C"] = (460, 25f),
        ["PBWA_M1_Solid_C"] = (500, 25f),
        ["PBWA_M1_StairF_C"] = (330, 25f),
        ["PBWA_M1_StairR_C"] = (370, 25f),
        ["PBWA_M1_StairT_C"] = (350, 25f),
        ["PBWA_M1_StairW_C"] = (460, 25f),
        ["PBWA_M1_WindowC_C"] = (480, 25f),
        ["PBWA_M1_WindowSide_C"] = (480, 25f),
        ["PBWA_M1_Windows_C"] = (460, 25f),
        ["PBWA_S1_ArchwayLargeSupport_C"] = (160, 12f),
        ["PBWA_S1_ArchwayLarge_C"] = (230, 12f),
        ["PBWA_S1_Archway_C"] = (280, 12f),
        ["PBWA_S1_BalconyD_C"] = (210, 12f),
        ["PBWA_S1_BalconyI_C"] = (230, 12f),
        ["PBWA_S1_BalconyO_C"] = (150, 12f),
        ["PBWA_S1_BalconyS_C"] = (210, 12f),
        ["PBWA_S1_Brace_C"] = (280, 12f),
        ["PBWA_S1_DoorC_C"] = (290, 12f),
        ["PBWA_S1_DoorS_C"] = (280, 12f),
        ["PBWA_S1_DoorSide_C"] = (290, 12f),
        ["PBWA_S1_Floor_C"] = (280, 12f),
        ["PBWA_S1_HalfWallDoorSide_C"] = (220, 12f),
        ["PBWA_S1_HalfWallDoor_C"] = (220, 12f),
        ["PBWA_S1_HalfWallHalf_C"] = (210, 12f),
        ["PBWA_S1_HalfWallS_C"] = (230, 12f),
        ["PBWA_S1_Pillar_C"] = (220, 12f),
        ["PBWA_S1_QuarterWallHalf_C"] = (150, 12f),
        ["PBWA_S1_QuarterWallS_C"] = (160, 12f),
        ["PBWA_S1_RoofC_C"] = (280, 12f),
        ["PBWA_S1_RoofD_C"] = (280, 12f),
        ["PBWA_S1_RoofI_C"] = (280, 12f),
        ["PBWA_S1_RoofO_C"] = (280, 12f),
        ["PBWA_S1_RoofS_C"] = (280, 12f),
        ["PBWA_S1_RoofWall_C"] = (280, 12f),
        ["PBWA_S1_Solid_C"] = (300, 12f),
        ["PBWA_S1_StairF_C"] = (210, 12f),
        ["PBWA_S1_StairR_C"] = (230, 12f),
        ["PBWA_S1_StairT_C"] = (220, 12f),
        ["PBWA_S1_StairW_C"] = (280, 12f),
        ["PBWA_S1_WindowsC_C"] = (290, 12f),
        ["PBWA_S1_WindowsSide_C"] = (290, 12f),
        ["PBWA_S1_Windows_C"] = (280, 12f),
        ["PBWA_W1_ArchwayLargeSupport_C"] = (100, 4f),
        ["PBWA_W1_ArchwayLarge_C"] = (125, 4f),
        ["PBWA_W1_Archway_C"] = (140, 4f),
        ["PBWA_W1_BalconyD_C"] = (115, 4f),
        ["PBWA_W1_BalconyI_C"] = (125, 4f),
        ["PBWA_W1_BalconyO_C"] = (95, 4f),
        ["PBWA_W1_BalconyS_C"] = (115, 4f),
        ["PBWA_W1_Brace_C"] = (140, 4f),
        ["PBWA_W1_DoorC_C"] = (145, 4f),
        ["PBWA_W1_DoorS_C"] = (140, 4f),
        ["PBWA_W1_DoorSide_C"] = (145, 4f),
        ["PBWA_W1_Floor_C"] = (140, 4f),
        ["PBWA_W1_HalfWallDoorS_C"] = (120, 4f),
        ["PBWA_W1_HalfWallDoor_C"] = (120, 4f),
        ["PBWA_W1_HalfWallHalf_C"] = (115, 4f),
        ["PBWA_W1_HalfWallS_C"] = (125, 4f),
        ["PBWA_W1_Pillar_C"] = (120, 4f),
        ["PBWA_W1_QuarterWallHalf_C"] = (95, 4f),
        ["PBWA_W1_QuarterWallS_C"] = (100, 4f),
        ["PBWA_W1_RoofC_C"] = (140, 4f),
        ["PBWA_W1_RoofD_C"] = (140, 4f),
        ["PBWA_W1_RoofI_C"] = (140, 4f),
        ["PBWA_W1_RoofO_C"] = (140, 4f),
        ["PBWA_W1_RoofS_C"] = (140, 4f),
        ["PBWA_W1_RoofWall_C"] = (140, 4f),
        ["PBWA_W1_Solid_C"] = (150, 4f),
        ["PBWA_W1_StairF_C"] = (115, 4f),
        ["PBWA_W1_StairR_C"] = (125, 4f),
        ["PBWA_W1_StairSpiral_C"] = (125, 4f),
        ["PBWA_W1_StairT_C"] = (120, 4f),
        ["PBWA_W1_StairW_C"] = (140, 4f),
        ["PBWA_W1_WindowC_C"] = (145, 4f),
        ["PBWA_W1_WindowSide_C"] = (145, 4f),
        ["PBWA_W1_Windows_C"] = (140, 4f),
    };

    /// <summary>
    ///     Default.BuildingInitialHealthPercent_* from AthenaGameData - the fraction of max health a
    ///     piece starts at while it builds in. This project used a single hardcoded 0.15 for every
    ///     material; the real game uses a different number per material.
    /// </summary>
    public static float InitialHealthPercent(EBuildingMaterial material) => material switch {
        EBuildingMaterial.Wood => 0.6f,
        EBuildingMaterial.Stone => 0.3333333f,
        EBuildingMaterial.Metal => 0.22f,
        _ => 0.6f
    };
}
