// <auto-generated> Tools/PakReader `spawnpoints FortPlayerStartWarmup` - do not edit by hand.
//
// Every AFortPlayerStartWarmup on the Athena map, in WORLD coordinates - i.e. the spawn island's
// player starts, the same actor class Project-Reboot-3.0 finds with
// GetAllActorsOfClass(FortPlayerStartWarmup).
//
// THESE ARE WORLD COORDINATES AND THAT IS THE ENTIRE POINT. An earlier attempt at this used
// (6816, 2420, 92), which is a FortPlayerStartWarmup's coordinate as stored in
// Athena_POI_Lobby_004 - but that is SUBLEVEL-LOCAL space. The island is placed by
// LF_Athena_POI_50x50_446 at (-125440, -113664, 3840) (yaw 0), so the local coordinate used as a
// world one drops the player into the middle of the map at an underground Z, and they fall to the
// ocean plane at Z=-5042. That was read at the time as a level-streaming failure; it was not.
//
// With the foundation transform applied, all 121 land where they should - X -143931..-113377,
// Y -124969..-103444, Z 3917..5141, the far corner of the map where Athena's spawn island sits.

namespace AFortOnlineBeacon.Net.Actors;

internal static partial class FortWarmupStarts {
    /// <summary>121 starts, flattened to X,Y,Z triples to keep the file small.</summary>
    public static readonly float[] Starts = {
        -116631f, -121265f, 3956f, -116919f, -121265f, 3956f, -118624f, -111244f, 3932f, -118336f, -111244f, 3932f,
        -125121f, -103911f, 3932f, -124855f, -103801f, 3932f, -116483f, -121593f, 3956f, -116771f, -121593f, 3956f,
        -118773f, -110916f, 3941f, -117059f, -121593f, 3956f, -118485f, -110916f, 3941f, -116483f, -120945f, 3956f,
        -116771f, -120945f, 3956f, -118197f, -110916f, 3941f, -117059f, -120945f, 3964f, -118772f, -111564f, 3932f,
        -118484f, -111564f, 3932f, -118196f, -111564f, 3932f, -125383f, -103665f, 3932f, -125117f, -103555f, 3932f,
        -124851f, -103444f, 3932f, -125135f, -104264f, 3936f, -124869f, -104153f, 3932f, -124603f, -104043f, 3934f,
        -124578f, -120746f, 4316f, -124865f, -120771f, 4316f, -124402f, -121059f, 4316f, -124689f, -121084f, 4316f,
        -124976f, -121110f, 4316f, -124459f, -120414f, 4316f, -124746f, -120439f, 4316f, -125033f, -120464f, 4316f,
        -130211f, -124641f, 5098f, -130499f, -124641f, 5100f, -130063f, -124969f, 5131f, -130351f, -124969f, 5141f,
        -130639f, -124969f, 5140f, -130063f, -124321f, 5094f, -130351f, -124321f, 5089f, -130639f, -124321f, 5087f,
        -140847f, -118734f, 4700f, -141020f, -118504f, 4700f, -141020f, -119050f, 4700f, -141193f, -118820f, 4700f,
        -141366f, -118590f, 4709f, -140502f, -118660f, 4700f, -140676f, -118430f, 4700f, -140849f, -118200f, 4700f,
        -143571f, -112259f, 4316f, -143459f, -111994f, 4316f, -143931f, -112268f, 4313f, -143819f, -112003f, 4314f,
        -143707f, -111737f, 4312f, -143334f, -112520f, 4316f, -143222f, -112255f, 4316f, -143110f, -111990f, 4316f,
        -129506f, -112772f, 3964f, -129528f, -112485f, 3964f, -129821f, -112945f, 3964f, -129844f, -112658f, 3964f,
        -129866f, -112371f, 3964f, -129175f, -112894f, 3964f, -129198f, -112607f, 3964f, -129220f, -112320f, 3964f,
        -138578f, -123443f, 4988f, -138742f, -123207f, 4982f, -116327f, -121265f, 3956f, -117223f, -121265f, 3962f,
        -118928f, -111245f, 3932f, -118032f, -111243f, 3932f, -125402f, -104028f, 3934f, -124574f, -103685f, 3935f,
        -124275f, -120719f, 4316f, -125168f, -120797f, 4325f, -129907f, -124641f, 5098f, -130803f, -124641f, 5098f,
        -140664f, -118977f, 4700f, -141203f, -118262f, 4700f, -143689f, -112539f, 4316f, -143341f, -111714f, 4316f,
        -129482f, -113075f, 3964f, -129552f, -112182f, 3964f, -138763f, -123752f, 4991f, -138927f, -123515f, 5000f,
        -139091f, -123279f, 5020f, -138230f, -123383f, 5011f, -138394f, -123146f, 4984f, -138559f, -122909f, 4968f,
        -138404f, -123693f, 5001f, -138915f, -122957f, 4976f, -113733f, -117316f, 3917f, -113810f, -117594f, 3917f,
        -113377f, -117262f, 3917f, -113455f, -117539f, 3917f, -113532f, -117817f, 3917f, -114001f, -117088f, 3917f,
        -114079f, -117365f, 3917f, -114156f, -117642f, 3917f, -113651f, -117024f, 3917f, -113892f, -117887f, 3917f,
        -130121f, -105447f, 4304f, -129855f, -105337f, 4304f, -130383f, -105201f, 4281f, -130117f, -105091f, 4284f,
        -129851f, -104980f, 4268f, -130135f, -105800f, 4306f, -129869f, -105689f, 4306f, -129603f, -105579f, 4302f,
        -130402f, -105564f, 4298f, -129574f, -105221f, 4286f, -118336f, -111808f, 3932f, -137052f, -109508f, 5092f,
        -137047f, -109220f, 5092f, -137383f, -109650f, 5092f, -137378f, -109362f, 5092f, -137372f, -109074f, 5092f,
        -136735f, -109662f, 5092f, -136730f, -109374f, 5092f, -136724f, -109087f, 5092f, -137058f, -109812f, 5092f,
        -137041f, -108916f, 5092f
    };
}
