// <auto-generated> Tools/ProjectileTable/gen_throw_speeds.py from `pakreader grenadespeeds` - do not edit by hand. </auto-generated>
//
// How fast each throw ability actually throws, for the 9 abilities that override the family's
// 4000. Everything absent from this table inherits that number - a cooked Blueprint stores only
// what it changes, so silence here IS the answer rather than a gap.
//
// Min and Max are both kept because the real ability interpolates between them by throw pitch
// (CalcGrenadeSpeedFromPitch); every one of them happens to set the two equal, which is why one
// number has been enough so far.

namespace AFortOnlineBeacon.Net.Actors;

internal static partial class FortThrowSpeeds {
    private static readonly (string Ability, float Min, float Max)[] Rows = {
        ("GA_Athena_AppleSauce_GrenadeWithTrajectory_C", 3800f, 3800f),
        ("GA_Athena_Ashton_DeepDishHome_C", 6000f, 6000f),
        ("GA_Athena_BoomBox_BGAWithTrajectory_C", 1500f, 1500f),
        ("GA_Athena_C4_C", 2500f, 2500f),
        ("GA_Athena_DogSweater_WithTrajectory_C", 3000f, 3000f),
        ("GA_Athena_FireworksMortar_WithTrajectory_C", 2500f, 2500f),
        ("GA_Athena_GasGrenade_WithTrajectory_C", 4000f, 4000f),
        ("GA_Athena_Grenade_WithTrajectory_C", 4000f, 4000f),
        ("GA_Athena_StickyGrenade_WithTrajectory_C", 6000f, 6000f),
    };
}
