// GENERATED by Tools/ConsumableTable/gen_consumables.py - do not edit by hand.
// Source: the 10.40 paks. Item definitions and ability CDOs from a CUE4Parse dump of
// FortniteGame/Content/Athena/Items/Consumables/, heal amounts from the AthenaGameData curve table
// rows those abilities name. See the script's docstring for the exact commands.

namespace AFortOnlineBeacon.Net.Actors;

/// <summary>
///     What a healing consumable does, and the two things needed to make it usable at all.
///
///     A consumable is a WEAPON in Fortnite's model - FortWeaponRangedItemDefinition, with a
///     WeaponActorClass to hold and a PrimaryFireAbility to fire - which is why equipping and using
///     one runs through exactly the same machinery as an assault rifle
///     (APawn.EquipInventoryItem grants the ability, the client activates it by spec handle). The
///     only thing this adds is what happens WHEN it activates.
///
///     Amounts are READ, not assumed. Each ability names AthenaGameData curve rows
///     (Default.ShieldSmallAmount = 25, Default.ShieldSmallCap = 0.5) and the cap is a FRACTION of
///     the maximum, not an absolute value - so a Small Shield Potion heals 25 shields but stops at
///     half of MaxShield, which is the rule the real game plays by.
/// </summary>
internal static class FortConsumables {
    /// <summary>
    ///     One healing consumable. A cap of NaN means "no cap" - fill to the pool's maximum.
    ///     TriggerDuration is how long the client's use animation takes; the server does not gate on
    ///     it yet, but a real one refuses a second activation until it has elapsed.
    /// </summary>
    internal readonly record struct FConsumableEffect(
        string DisplayName,
        bool HealsHealth, float HealthAmount, float HealthCapFraction,
        bool HealsShields, float ShieldAmount, float ShieldCapFraction,
        float TriggerDuration,
        float OverTimeTotal, float OverTimePerTick, float OverTimeTickRate);

    /// <summary>Item definition name -> its healing effect. 6 entries.</summary>
    private static readonly Dictionary<string, FConsumableEffect> Effects = new(StringComparer.OrdinalIgnoreCase) {
        ["Athena_Bandage"] = new("Bandage", true, 15f, 0.75f, false, float.NaN, float.NaN, 3.53f, float.NaN, float.NaN, float.NaN),
        ["Athena_Medkit"] = new("Med Kit", true, 100f, float.NaN, false, float.NaN, float.NaN, 10.03f, float.NaN, float.NaN, float.NaN),
        ["Athena_PurpleStuff"] = new("Slurp Juice", false, float.NaN, float.NaN, true, float.NaN, float.NaN, 2.03f, 75f, 1f, 0.5f),
        ["Athena_ShieldSmall"] = new("Small Shield Potion", false, float.NaN, float.NaN, true, 25f, 0.5f, 2.03f, float.NaN, float.NaN, float.NaN),
        ["Athena_Shields"] = new("Shield Potion", false, float.NaN, float.NaN, true, 50f, float.NaN, 5.03f, float.NaN, float.NaN, float.NaN),
        ["Athena_SuperMedkit"] = new("Chug Jug", true, 100f, float.NaN, true, 100f, float.NaN, 15.03f, float.NaN, float.NaN, float.NaN),
    };

    /// <summary>Item definition name -> the actor the pawn holds while using it.</summary>
    private static readonly Dictionary<string, string> ActorClasses = new(StringComparer.OrdinalIgnoreCase) {
        ["Athena_Bandage"] = "/Game/Abilities/Player/Generic/UtilityItems/B_ConsumableSmall_Bandages_Athena.B_ConsumableSmall_Bandages_Athena_C",
        ["Athena_Medkit"] = "/Game/Abilities/Player/Generic/UtilityItems/B_ConsumableSmall_Medkit_Athena.B_ConsumableSmall_Medkit_Athena_C",
        ["Athena_PurpleStuff"] = "/Game/Abilities/Player/Generic/UtilityItems/B_ConsumableSmall_SlurpJuice_Athena.B_ConsumableSmall_SlurpJuice_Athena_C",
        ["Athena_ShieldSmall"] = "/Game/Abilities/Player/Generic/UtilityItems/B_ConsumableSmall_MiniShield_Athena.B_ConsumableSmall_MiniShield_Athena_C",
        ["Athena_Shields"] = "/Game/Abilities/Player/Generic/UtilityItems/B_ConsumableSmall_HalfShield_Athena.B_ConsumableSmall_HalfShield_Athena_C",
        ["Athena_SuperMedkit"] = "/Game/Abilities/Player/Generic/UtilityItems/B_UtilityItem_Generic_Athena.B_UtilityItem_Generic_Athena_C",
    };

    /// <summary>
    ///     Item definition name -> its own asset path, in the "package.object" form an
    ///     object reference needs on the wire. Loot tables carry full paths already; this is
    ///     for naming a consumable by its short name (STARTING_CONSUMABLES, a console command).
    /// </summary>
    private static readonly Dictionary<string, string> ItemPaths = new(StringComparer.OrdinalIgnoreCase) {
        ["Athena_Bandage"] = "/Game/Athena/Items/Consumables/Bandage/Athena_Bandage.Athena_Bandage",
        ["Athena_Medkit"] = "/Game/Athena/Items/Consumables/Medkit/Athena_Medkit.Athena_Medkit",
        ["Athena_PurpleStuff"] = "/Game/Athena/Items/Consumables/PurpleStuff/Athena_PurpleStuff.Athena_PurpleStuff",
        ["Athena_ShieldSmall"] = "/Game/Athena/Items/Consumables/ShieldSmall/Athena_ShieldSmall.Athena_ShieldSmall",
        ["Athena_Shields"] = "/Game/Athena/Items/Consumables/Shields/Athena_Shields.Athena_Shields",
        ["Athena_SuperMedkit"] = "/Game/Athena/Items/Consumables/SuperMedkit/Athena_SuperMedkit.Athena_SuperMedkit",
    };

    /// <summary>Item definition name -> the UGameplayAbility class granted on equip.</summary>
    private static readonly Dictionary<string, string> Abilities = new(StringComparer.OrdinalIgnoreCase) {
        ["Athena_Bandage"] = "/Game/Athena/Items/Consumables/Bandage/GA_Athena_Bandage.GA_Athena_Bandage_C",
        ["Athena_Medkit"] = "/Game/Athena/Items/Consumables/Medkit/GA_Athena_Medkit.GA_Athena_Medkit_C",
        ["Athena_PurpleStuff"] = "/Game/Athena/Items/Consumables/PurpleStuff/GA_Athena_PurpleStuff.GA_Athena_PurpleStuff_C",
        ["Athena_ShieldSmall"] = "/Game/Athena/Items/Consumables/ShieldSmall/GA_Athena_ShieldSmall.GA_Athena_ShieldSmall_C",
        ["Athena_Shields"] = "/Game/Athena/Items/Consumables/Shields/GA_Athena_Shields.GA_Athena_Shields_C",
        ["Athena_SuperMedkit"] = "/Game/Athena/Items/Consumables/SuperMedkit/GA_Athena_SuperMedkit.GA_Athena_SuperMedkit_C",
    };

    public static string? ActorClassFor(string itemDefinitionName) =>
        ActorClasses.GetValueOrDefault(itemDefinitionName);

    public static string? AbilityFor(string itemDefinitionName) =>
        Abilities.GetValueOrDefault(itemDefinitionName);

    public static string? ItemPathFor(string itemDefinitionName) =>
        ItemPaths.GetValueOrDefault(itemDefinitionName);

    public static FConsumableEffect? EffectFor(string itemDefinitionName) =>
        Effects.TryGetValue(itemDefinitionName, out var effect) ? effect : null;

    /// <summary>Every item definition name this table covers - used to answer "is this a consumable".</summary>
    public static IEnumerable<string> Names => Effects.Keys;
}
