// <auto-generated> Tools/PakReader `placements Spawner_C` + AthenaGameData - do not edit by hand.
//
// Every drivable-vehicle spawner placed on the Athena map, in WORLD coordinates, with the yaw the
// spawned VEHICLE ends up with and the share of that type's spawners the game data says to use.
//
// 1. THE SPAWNER CLASS IS NOT THE VEHICLE CLASS. Each Athena_*Spawner_C Blueprint carries a
//    VehicleClass soft reference in its CDO, and that is what gets spawned.
//
// 2. THE +90 IS NOT A FUDGE. Athena_VehicleSpawner_C::SpawnVehicle, disassembled with
//    Tools/BlueprintDump, builds the spawn transform as
//
//        ComposeTransforms(MakeTransform(loc=0, rot=(P=0 Y=90 R=0), scale=1), GetTransform())
//
//    when its YAxisForward flag is set - the spawner meshes are authored with Y as forward. Five
//    of the seven set the flag; Quad and Octopus do not. Both branches of the graph (normal and
//    Ostrich) do the same thing, so there is no third case.
//
// 3. ONLY THE JACKAL ACTUALLY SPAWNS ON 10.40, and the data says so plainly once the indirection
//    is followed. DefaultMapInfo.VehicleClassDetails gives each vehicle a Min/MaxSpawnPercent as
//    an FScalableFloat whose curve row is in AthenaGameData - and the ROW NAMES ARE LEGACY, which
//    is the part that makes this easy to get wrong: the Jackal reads Default.HoverBoard.*, the
//    Octopus reads Default.HamsterBall.*, the Antelope reads Default.QuadBike.*. At index 0:
//
//        JackalVehicle_Athena_C       Default.HoverBoard.*  50%..50%
//        AntelopeVehicle_C            Default.QuadBike.*  0%..0%
//        ShoppingCartVehicleSK_C      Default.ShoppingCart.*  0%..0%
//        GolfCartVehicleSK_C          Default.GolfCart.*  0%..0%
//        OctopusVehicle_C             Default.HamsterBall.*  0%..0%
//        FerretVehicle_C              Default.BiPlane.*  0%..0%
//        PushCannon_C                 Default.Cannon.*  0%..0%
//
//    Everything but the Jackal is 0%, which is not a bug in the data - Season 10 vaulted the ATK,
//    the shopping cart, the golf cart, the plane, the baller and the cannon, and the Quadcrasher
//    (Jackal) is the one that stayed. The PR3.0 capture does contain a few of the others, but that
//    is a MODDED server ignoring the percentages, not evidence about the real game.
//
//    The 50% for the Jackal is also corroborated: the capture has 39 Jackals against 102 placed
//    spawners, and relevancy culling only ever trims that number.
//
// 325 spawners: Jackal 102, Quad 56, Cart 53, GolfCart 17, Octopus 47, Biplane 18, Cannon 32

namespace AFortOnlineBeacon.Net.Actors;

internal static partial class FortVehicleSpawns {
    /// <summary>One class path per Types entry - the VEHICLE, not the spawner.</summary>
    public static readonly string[] VehicleClasses = {
        "/Game/Athena/DrivableVehicles/JackalVehicle_Athena.JackalVehicle_Athena_C", // Athena_JackalSpawner_C
        "/Game/Athena/DrivableVehicles/AntelopeVehicle.AntelopeVehicle_C", // Athena_QuadSpawner_C
        "/Game/Athena/DrivableVehicles/ShoppingCartVehicleSK.ShoppingCartVehicleSK_C", // Athena_CartSpawner_C
        "/Game/Athena/DrivableVehicles/Golf_Cart/Golf_Cart_Base/Blueprints/GolfCartVehicleSK.GolfCartVehicleSK_C", // Athena_GolfCartSpawner_C
        "/Game/Athena/DrivableVehicles/Octopus/OctopusVehicle.OctopusVehicle_C", // Athena_OctopusSpawner_C
        "/Game/Athena/DrivableVehicles/Biplane/Blueprints/FerretVehicle.FerretVehicle_C", // Athena_BiplaneSpawner_C
        "/Game/Athena/DrivableVehicles/PushCannon.PushCannon_C", // Athena_CannonSpawner_C
    };

    /// <summary>
    ///     Percent of this type's spawners to use, from DefaultMapInfo x AthenaGameData at index 0.
    ///     Min and Max are equal for every row on this build, so one number says it all.
    /// </summary>
    public static readonly float[] SpawnPercents = {
        50f, // JackalVehicle_Athena_C (Default.HoverBoard.*)
        0f, // AntelopeVehicle_C (Default.QuadBike.*)
        0f, // ShoppingCartVehicleSK_C (Default.ShoppingCart.*)
        0f, // GolfCartVehicleSK_C (Default.GolfCart.*)
        0f, // OctopusVehicle_C (Default.HamsterBall.*)
        0f, // FerretVehicle_C (Default.BiPlane.*)
        0f, // PushCannon_C (Default.Cannon.*)
    };

    /// <summary>Index into VehicleClasses, one per spawn point.</summary>
    public static readonly byte[] Types = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
        4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5,
        5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
        6, 6, 6, 6, 6,
    };

    /// <summary>X, Y, Z, Yaw per spawn point - flattened to keep the file small.</summary>
    public static readonly float[] Spawns = {
        -69792f, -7952f, 1324f, 90.0f, -69688f, -7952f, 1324f, 90.0f, -69580f, -7952f, 1324f, 90.0f,
        -69472f, -7952f, 1324f, 90.0f, -63630f, -68836f, 3616f, -90.0f, -63536f, -68836f, 3616f, -90.0f,
        -63440f, -68836f, 3616f, -90.0f, -63346f, -68836f, 3616f, -90.0f, -62808f, -99620f, 1992f, 90.0f,
        -62600f, -99500f, 1924f, 61.9f, -59392f, -70088f, 6380f, 0.0f, -54680f, -105224f, 1904f, -135.0f,
        -53404f, -90512f, 7368f, 90.0f, -53096f, -90604f, 7300f, -132.2f, -52496f, -121008f, 768f, -28.1f,
        -52444f, -88952f, 7364f, 180.0f, -52440f, -121124f, 836f, 180.0f, -52408f, -90248f, 7300f, 90.0f,
        -42728f, -107220f, 8516f, -90.0f, -42708f, -96652f, 6972f, 180.0f, -42688f, -95236f, 6152f, 129.4f,
        -42676f, -95464f, 6220f, -90.0f, -42364f, -95072f, 6212f, 0.0f, -42360f, -95000f, 6220f, 0.0f,
        -42344f, -106768f, 8452f, 112.5f, -42112f, -106624f, 8508f, 157.5f, -41784f, -106704f, 8516f, -90.0f,
        -41504f, -96160f, 6600f, 0.0f, -36568f, -127268f, 7748f, 180.0f, -35936f, -120488f, 7684f, -163.1f,
        -35752f, -120540f, 7756f, -90.0f, -34436f, 76637f, 2164f, -118.7f, -34218f, 76552f, 2142f, -76.1f,
        -30040f, -108240f, 7752f, -90.0f, -29988f, -116008f, 7748f, 90.0f, -29872f, -115952f, 7680f, -118.1f,
        -29816f, -108664f, 7688f, -56.2f, -26404f, -117544f, 7748f, 90.0f, -18648f, -105252f, 6980f, 180.0f,
        -11600f, -38300f, 1096f, 90.0f, -11599f, -38776f, 1219f, 136.7f, -11240f, -38288f, 1188f, -2.8f,
        -11240f, -38152f, 1176f, 8.4f, -7384f, -124216f, 6988f, 180.0f, -4316f, -77016f, 3908f, -90.0f,
        1696f, -119228f, 6528f, 70.3f, 1780f, -119380f, 6596f, 0.0f, 5928f, -131876f, 3908f, 180.0f,
        12501f, 71997f, 1453f, -11.5f, 14233f, 71800f, 1292f, -112.4f, 14314f, 71767f, 1297f, -112.4f,
        14392f, 71735f, 1302f, -112.4f, 21325f, -63009f, 3154f, 144.0f, 21381f, -62932f, 3185f, 144.0f,
        22104f, -57560f, 4448f, 132.2f, 22464f, -57708f, 4504f, 50.6f, 25884f, 46450f, 1312f, 180.0f,
        25884f, 46544f, 1312f, 180.0f, 25884f, 46640f, 1312f, 180.0f, 25884f, 46734f, 1312f, 180.0f,
        41396f, -69476f, 3156f, -46.5f, 41744f, -69132f, 3176f, -45.0f, 41816f, -69052f, 3176f, -54.8f,
        41824f, -69796f, 3228f, 30.9f, 42560f, 12193f, 2036f, -132.2f, 42661f, 12969f, 2205f, 50.6f,
        42664f, 12065f, 2044f, -140.6f, 42752f, 12896f, 2175f, 50.6f, 50532f, 56024f, 5452f, 90.0f,
        51744f, 55880f, 5376f, -149.1f, 55416f, -89520f, 11160f, 146.3f, 55538f, -89410f, 11108f, 90.0f,
        56302f, -90058f, 11182f, -56.2f, 56476f, -89472f, 11104f, 42.2f, 65891f, -27928f, -760f, -123.4f,
        66077f, -27929f, -760f, -100.9f, 66211f, -27991f, -760f, -86.9f, 66372f, -27957f, -760f, -67.2f,
        82440f, 74848f, 3464f, 28.1f, 82600f, 74968f, 3528f, 90.0f, 83232f, 74552f, 4304f, 180.0f,
        83296f, 74392f, 4232f, -143.4f, 90592f, -67160f, 2380f, -126.6f, 91380f, -68264f, 2656f, 16.9f,
        91396f, -68424f, 2584f, -42.3f, 91440f, -67004f, 2372f, 78.9f, 111512f, 35048f, 1156f, 42.2f,
        111520f, 35176f, 1156f, 73.1f, 113160f, 37792f, 1536f, 146.2f, 113312f, 37800f, 1536f, 104.1f,
        113448f, 19240f, 1608f, -90.0f, 114016f, 19616f, 1544f, 19.7f, 117552f, 36536f, 2000f, 180.0f,
        117600f, 36440f, 1928f, -132.2f, 117640f, 35200f, 1156f, -163.1f, 117784f, 35200f, 1156f, -126.6f,
        122224f, 60912f, 1544f, 109.7f, 122248f, 61008f, 1544f, 137.8f, 122256f, 32408f, 3840f, 140.6f,
        122472f, 32280f, 3912f, -90.0f, 122792f, -4584f, 832f, 180.0f, 122888f, -4720f, 768f, -70.3f,
        -71760f, -34908f, 1920f, -120.0f, -69056f, -8188f, 1160f, 0.0f, -64050f, 36503f, 1920f, 96.4f,
        -63407f, -68159f, 3530f, -93.6f, -59274f, -73926f, 3547f, 84.3f, -37548f, 76170f, 2083f, 45.7f,
        -37270f, 76479f, 2145f, 45.7f, -36308f, 2168f, 1152f, -105.9f, -33740f, 75436f, 2096f, -163.1f,
        -33620f, 74680f, 2096f, -177.2f, -29656f, -119816f, 4616f, 0.0f, -29648f, -120320f, 4616f, 0.0f,
        -25288f, 54004f, 1216f, -39.4f, -11871f, -38436f, 1162f, 125.9f, -11149f, -37414f, 1114f, 100.6f,
        -928f, 1120f, 0f, 180.0f, -569f, -97641f, 1619f, 2.7f, -458f, -96338f, 1616f, -31.7f,
        520f, -97844f, 1536f, -150.0f, 520f, -97668f, 1536f, -150.0f, 520f, -97488f, 1536f, -150.0f,
        4682f, -4558f, 2065f, -90.0f, 4892f, -4558f, 2065f, 90.0f, 5126f, -4558f, 2065f, -90.0f,
        5330f, -4558f, 2065f, 90.0f, 12380f, 73259f, 1190f, 180.0f, 12481f, 72729f, 1169f, -179.3f,
        12776f, 70212f, 1152f, 90.0f, 12849f, 73001f, 1168f, 180.0f, 21615f, -62627f, 3246f, 46.0f,
        21985f, -57292f, 4538f, 159.5f, 26360f, 46602f, 1160f, -17.9f, 33024f, 64128f, 1152f, 120.9f,
        33690f, 62878f, 1245f, -163.2f, 35707f, 60316f, 1245f, 120.9f, 36032f, 60416f, 1152f, -84.4f,
        36136f, -135672f, 1920f, -128.4f, 41193f, -69792f, 3179f, -146.3f, 41443f, -70039f, 3180f, -146.3f,
        42943f, 11575f, 2099f, -38.9f, 43037f, 12666f, 2079f, -44.3f, 55933f, -127533f, 1920f, -35.0f,
        56196f, -89340f, 11108f, 92.8f, 56210f, -127828f, 1920f, -60.0f, 56371f, 71550f, 1923f, -11.3f,
        56371f, 71760f, 1923f, 0.0f, 65828f, -27240f, -672f, 47.3f, 66731f, -27690f, -675f, 129.0f,
        90020f, -66886f, 2404f, 146.2f, 90987f, -66792f, 2401f, 160.5f, 93568f, -116340f, 2688f, 120.0f,
        93760f, -116228f, 2688f, 100.0f, 112256f, 37768f, 1152f, 180.0f, 112256f, 37976f, 1152f, 168.7f,
        122880f, 60416f, 1536f, -115.3f, 132026f, -83962f, 1542f, 0.0f, -78496f, -7854f, 4f, -98.4f,
        -77892f, -13152f, 388f, -36.6f, -72572f, -12636f, 8f, 78.7f, -69266f, -6980f, 4f, 33.8f,
        -47796f, 65458f, 1538f, -123.2f, -46976f, -56000f, 7520f, -16.9f, -46766f, -64674f, 5369f, -162.8f,
        -46576f, -55968f, 7520f, 71.8f, -46240f, -55376f, 7520f, -73.1f, -44509f, -42339f, -764f, 158.0f,
        -37826f, 73880f, 1907f, 31.2f, -31746f, -60596f, 1924f, -11.3f, -29664f, 54560f, 1160f, 123.8f,
        -28540f, 22764f, 12674f, 64.7f, -27290f, -60774f, 1922f, -16.9f, -27252f, 21846f, 13062f, -67.5f,
        -26656f, 53504f, 1160f, -101.3f, -22168f, -23336f, 5114f, 157.5f, -21508f, -26960f, 4994f, 163.1f,
        -19510f, -50824f, 4f, -174.4f, -18602f, -29378f, 5020f, -98.4f, -16040f, -52128f, 2f, -90.0f,
        -1038f, 54201f, 1920f, -118.6f, -360f, -13616f, 2690f, -84.4f, 670f, -96354f, 1544f, -70.3f,
        5974f, -13792f, 2688f, -92.8f, 8092f, -6300f, 1922f, -135.0f, 19016f, 41992f, 1152f, -118.1f,
        21664f, 43265f, 1152f, -146.2f, 22688f, 45376f, 1160f, -73.1f, 22992f, 44576f, 1152f, 14.1f,
        24096f, 39314f, 1152f, -135.0f, 27136f, 41457f, 1152f, -22.5f, 28720f, 40142f, 1160f, 8.4f,
        29804f, 39894f, 1160f, 3.0f, 46208f, -5760f, 768f, 33.8f, 55654f, -89222f, 11106f, 36.6f,
        55968f, -90025f, 11106f, -165.9f, 69984f, -56934f, 2f, 90.0f, 75401f, -106015f, 4226f, -67.5f,
        75677f, -105921f, 4226f, 64.7f, 76820f, -84334f, 2312f, 157.5f, 77188f, -104940f, 4226f, -115.3f,
        95422f, -115350f, 2689f, 159.0f, 95676f, -83804f, 2312f, -165.9f, 115502f, -101296f, 8580f, 42.2f,
        127617f, -105471f, 1920f, 146.2f, 130246f, -104095f, 1923f, -74.5f, 132234f, -102020f, 1922f, -90.0f,
        133230f, -107382f, 1924f, 143.4f, 136178f, -92231f, 1536f, -118.6f, 138496f, -109440f, 4992f, 106.9f,
        140342f, -92080f, 1540f, 90.0f, -58282f, 19900f, 1540f, 180.0f, -55229f, 36905f, 1141f, -103.8f,
        -53348f, 22032f, 1544f, 180.0f, -28659f, 57248f, 1160f, -100.1f, -27206f, 50840f, 1160f, -66.0f,
        -27191f, 56293f, 1160f, -142.0f, 7676f, 82172f, 1366f, -90.0f, 8188f, 81144f, 1156f, -90.0f,
        8532f, 82844f, 1156f, -28.1f, 8712f, 81388f, 1156f, -104.1f, 11498f, 68483f, 1296f, -160.7f,
        38352f, -132696f, 1928f, 73.1f, 41328f, -141040f, 2256f, 55.8f, 46702f, -133046f, 1928f, 35.6f,
        51752f, -126872f, 1928f, -177.2f, 54384f, -124448f, 1920f, 64.7f, 129533f, -104454f, 1924f, -93.0f,
        -51120f, -81312f, 3920f, -112.5f, -51080f, -80936f, 3880f, -81.6f, -50864f, -81184f, 3904f, -81.6f,
        -50816f, -80768f, 3864f, -91.6f, -40064f, -60928f, 5760f, -112.5f, -39808f, -60800f, 5760f, -81.6f,
        -39040f, -61056f, 5760f, -126.6f, -38912f, -61312f, 5760f, -92.8f, -38784f, -60928f, 5760f, -56.3f,
        -36864f, -127480f, 7692f, 0.0f, -29440f, -126200f, 5376f, 0.0f, -29440f, -125688f, 5376f, 0.0f,
        -28928f, -126200f, 5376f, 0.0f, -28928f, -125688f, 5376f, 0.0f, -26616f, -117248f, 7692f, -90.0f,
        -18944f, -105464f, 6924f, 0.0f, -4104f, -77312f, 3852f, 90.0f, 5632f, -132088f, 3852f, 0.0f,
        48256f, 58368f, 4992f, -90.0f, 48512f, 58752f, 4992f, -56.2f, 48640f, 59008f, 4992f, -47.8f,
        49024f, 58880f, 4992f, -25.3f, 49280f, 59264f, 4992f, 0.0f, 69098f, 24136f, 7688f, -35.0f,
        75711f, -104667f, 4312f, 177.2f, 75756f, -104573f, 4256f, 66.2f, 76184f, -104960f, 4616f, -11.3f,
        83328f, 74240f, 3468f, 0.0f, 83328f, 74752f, 3468f, 0.0f, 83584f, 74240f, 3468f, 0.0f,
        83584f, 74752f, 3468f, 0.0f, 98698f, -6130f, -2672f, 39.5f, 98864f, -6096f, -2680f, -47.8f,
        102720f, -68096f, 6912f, -171.6f, 102912f, -68224f, 6912f, -149.1f, 103296f, -68736f, 6912f, -126.6f,
        103552f, -68480f, 6912f, -95.6f, 103808f, -68608f, 6912f, -47.8f, 113152f, 18944f, 1544f, 89.9f,
        113152f, 34304f, 1152f, 90.0f, 113152f, 35328f, 1152f, -90.0f, 113504f, 37792f, 1164f, 0.0f,
        113504f, 38016f, 1164f, 0.0f, 113664f, 34304f, 1152f, 90.0f, 113664f, 35328f, 1152f, -90.0f,
        118016f, 35584f, 1152f, 180.0f, 121856f, 61312f, 1548f, 90.0f, -68185f, -113849f, -2300f, -41.6f,
        -54149f, -105045f, 2664f, -135.0f, -49864f, -111952f, 7256f, -161.2f, -42626f, -63021f, 5464f, -59.1f,
        -41731f, -62484f, 5566f, -59.1f, -40836f, -61948f, 5668f, -59.1f, -27136f, -131472f, 5380f, 170.0f,
        -26556f, -130668f, 5380f, 170.0f, -25844f, -129836f, 5380f, 170.0f, -25172f, -128812f, 5380f, 170.0f,
        -24564f, -127852f, 5380f, 170.0f, 31740f, 92154f, 1538f, 180.0f, 48352f, 57668f, 5004f, -61.9f,
        49508f, 58296f, 5004f, -61.9f, 50556f, 58908f, 5004f, -61.9f, 100530f, -71493f, 6497f, -53.5f,
        101436f, -70811f, 6578f, -50.6f, 102319f, -70128f, 6806f, -50.6f, -27218f, -109798f, 8638f, -179.4f,
        69056f, 24000f, 8457f, -135.0f, 69056f, 24640f, 8457f, 135.0f, 69696f, 24000f, 8457f, -45.0f,
        69696f, 24640f, 8457f, 45.0f, 75296f, -103996f, 4228f, 135.0f, 76284f, -106116f, 5000f, -90.0f,
        76772f, -103996f, 4228f, 45.0f, 76804f, -104820f, 6152f, 90.0f, 93574f, 572f, 384f, -101.3f,
        93862f, 592f, 384f, -84.4f, 94104f, 700f, 384f, -67.5f, 95168f, 960f, -1528f, -135.0f,
        95744f, -6784f, -2304f, -90.0f, 95744f, -5504f, -2304f, 90.0f, 96256f, -6784f, -2304f, -90.0f,
        96256f, -5504f, -2304f, 90.0f, 96646f, 47f, -2296f, -65.4f, 96768f, -6784f, -2304f, -90.0f,
        96768f, -5504f, -2304f, 90.0f, 96884f, 25f, -2296f, -65.4f, 97280f, -6784f, -2304f, -90.0f,
        97280f, -5504f, -2304f, 90.0f, 97600f, 512f, -1920f, -104.1f, 97792f, -6784f, -2304f, -90.0f,
        98304f, -6784f, -2304f, -90.0f, 98304f, -5504f, -2304f, 90.0f, 98816f, -6784f, -2304f, -90.0f,
        98816f, -5504f, -2304f, 90.0f, 100928f, 2496f, -1528f, -45.0f, 100928f, 3136f, -1528f, -4.1f,
        109271f, -15389f, -2732f, 112.5f,
    };
}
