// <auto-generated> Tools/ProjectileTable/gen_grenade_effects.py - do not edit by hand. </auto-generated>
//
// What a thrown item does BESIDES damage, read from the AthenaGameData curve table - the same
// table the projectile Blueprints themselves call EvaluateCurveTableRow against, so these are the
// values the game plays by rather than an impression of them.
//
// NOTE THE NAMES: Athena_KnockGrenade is the IMPULSE grenade and Athena_ShockGrenade is the
// SHOCKWAVE. Their tags and their asset folders say so, and the obvious reading is backwards.
//
// Damages is spelled out rather than read: an item's stat row does not say whether its ability
// applies it, and the boogie bomb's row IS the frag's (100/375) - see the generator's header.
//
// A zero means the family has no such row, not that the effect is off; see the Kind.

namespace AFortOnlineBeacon.Net.Actors;

/// <summary>What a thrown item does when it goes off, beyond its damage.</summary>
internal enum EGrenadeEffect { None, Knockback, Dance, Chill, Gas, Smoke, Sticky }

internal static partial class FortGrenadeEffects {
    private static readonly (string Item, EGrenadeEffect Kind, float Radius, float LaunchVelocity,
                             float AddToZ, float Duration, float Period, float HitDelay,
                             float DestroyDistance,
                             bool FriendlyFire, bool Damages, bool FallDamage)[] Rows = {
        // Impulse Grenade - lands, waits half a second, throws everyone. No damage at all.
        ("Athena_KnockGrenade", EGrenadeEffect.Knockback, 500f, 2500f, 50f, 0f, 0f, 0.5f, 0f, true, false, true),
        // Shockwave Grenade - the same but harder (3800), and nobody takes fall damage afterwards.
        ("Athena_ShockGrenade", EGrenadeEffect.Knockback, 500f, 3800f, 50f, 0f, 0f, 0.5f, 1400f, true, false, false),
        // Boogie Bomb - no damage; everyone in range dances for five seconds.
        ("Athena_DanceGrenade", EGrenadeEffect.Dance, 0f, 0f, 0f, 5f, 0f, 0f, 0f, true, false, true),
        // Chiller - a small launch plus slippery feet.
        ("Athena_IceGrenade", EGrenadeEffect.Chill, 500f, 1500f, 0f, 7f, 0f, 0.5f, 0f, true, false, true),
        // Stink Bomb - the blast does nothing; the CLOUD is what damages, every half second.
        ("Athena_GasGrenade", EGrenadeEffect.Gas, 512f, 0f, 0f, 9f, 0.5f, 0f, 0f, true, false, true),
        // Smoke Grenade - cover, and nothing else. Lifetime is its own row rather than a Duration.
        ("Athena_SmokeGrenade", EGrenadeEffect.Smoke, 0f, 0f, 0f, 20f, 0f, 0f, 0f, true, false, true),
        // Clinger - sticks where it lands and goes off 2.5s later, for real damage.
        ("Athena_StickyGrenade", EGrenadeEffect.Sticky, 0f, 0f, 0f, 0f, 0f, 2.5f, 0f, true, true, true),
    };
}
