using AFortOnlineBeacon.Core.Objects;
using AFortOnlineBeacon.Net.Rpc;

namespace AFortOnlineBeacon.Net.Actors;

/// <summary>
///     Turns a reported hit into wood, stone or metal.
///
///     The client tells this server what it hit as an object path and nothing more:
///     ".../Sublevel_X2Y3.PersistentLevel.Tree_Pine_169". An injected server would simply ask the
///     actor (ABuildingSMActor knows its own resource type); an external one has never heard of that
///     actor and never will - it lives in a streaming sublevel this server does not load.
///
///     So the answer is baked ahead of time from the shipped maps: every placed Blueprint actor in
///     Athena joined to its class, and every class to its CDO's ResourceType and amount tier. See
///     Tools/HarvestTable, which also documents why it takes TWO properties and not one.
///
///     One known soft spot, 90 classes of 2048: those carry no ResourceType of their own, so the
///     generator falls back to the family named by their amount curve. That is right for the case it
///     was built for (a tree with no override and a ResourceWoodLow curve) and wrong wherever a class
///     inherits its ResourceType from a PARENT Blueprint instead - a cooked child never re-serialises
///     an inherited value, so the property is simply absent. `Car_Pickup` coming out as wood rather
///     than metal is the visible symptom. Fixing it means walking the SuperStruct chain in the
///     generator; the other 1958 classes state their resource outright and are unaffected.
///
///     What this deliberately does NOT do is trust the hit. The client picked the target, the
///     position and the moment; a real server re-traces all of that. Nothing here is safe against a
///     modified client, and it should not be mistaken for something that is - see <see cref="Grant"/>.
/// </summary>
internal static partial class FortHarvestResources {
    /// <summary>
    ///     The three Athena resources, as their item definitions. Ordinary path-exported assets like
    ///     every other item this server names (see UAssetRegistry): the client already has them.
    /// </summary>
    private static readonly Dictionary<string, string> ItemPaths = new(StringComparer.OrdinalIgnoreCase) {
        ["Wood"] = "/Game/Items/ResourcePickups/WoodItemData.WoodItemData",
        ["Stone"] = "/Game/Items/ResourcePickups/StoneItemData.StoneItemData",
        ["Metal"] = "/Game/Items/ResourcePickups/MetalItemData.MetalItemData"
    };

    /// <summary>
    ///     How much one hit yields, per amount tier. FALLBACK ONLY, for a row
    ///     <see cref="RowAmounts"/> (the real curve table, baked by Tools/HarvestTable's pass 3) does
    ///     not cover - every row this project has actually seen live IS covered, so this should never
    ///     fire in practice, but the tier ordering is worth keeping as a safety net against a stem
    ///     whose row name pass 3 could not resolve.
    /// </summary>
    private static readonly Dictionary<string, int> TierAmounts = new(StringComparer.OrdinalIgnoreCase) {
        ["Low"] = 2,
        ["Medium"] = 3,
        ["High"] = 5,
        ["VeryHigh"] = 7,
        ["Normal"] = 3, // LDBuildingNormal - a prefab building wall or floor
        ["Thick"] = 5   // LDBuildingThick - the same, reinforced
    };

    /// <summary>
    ///     Generated by Tools/HarvestTable's pass 3: every row of
    ///     `/Game/Balance/DataTables/ResourceRates.uasset` (a UCurveTable) evaluated at time 0 - REAL
    ///     numbers, not placeholders, read straight out of the shipped game data.
    ///
    ///     What this number does NOT mean: real Fortnite (see `ABuildingSMActor::OnDamageServer` in
    ///     PriveDev's Erbium reimplementation) does not pay this value per hit - it pays
    ///     `Eval(0) * Damage / MaxHealth`, i.e. this is a FULL-BREAK total that gets divided down by
    ///     how much of the target's health one hit actually removed. This project has no real
    ///     per-class MaxHealth yet (`ABuildingActor.BaseHitPointsFor` is still a placeholder), so that
    ///     division can't be reproduced faithfully - using the raw Eval(0) as a flat per-hit amount is
    ///     a deliberate, documented simplification, not an attempt to be exact. What IS exact: the
    ///     RELATIVE proportions between rows (ResourceWoodVeryHigh really does yield ~7.6x
    ///     ResourceWoodLow, not the old TierAmounts' arbitrary 7:2), which is the part that was
    ///     previously fabricated.
    /// </summary>
    private static int AmountFor(string tier, string rowName) =>
        RowAmounts.TryGetValue(rowName, out var real)
            ? Math.Max(1, (int) MathF.Round(real))
            : TierAmounts.GetValueOrDefault(tier, 3);

    /// <summary>Fortnite's per-resource stack cap.</summary>
    private const int MaxResourceStack = 999;

    private static readonly HashSet<string> UnknownStemsSeen = new(StringComparer.OrdinalIgnoreCase);

    /// <summary>
    ///     Resolves a hit actor's path to the resource it yields, or null if it yields none - which
    ///     is most of the world: terrain, roads, and anything with no BuildingResourceAmountOverride
    ///     at all.
    /// </summary>
    public static (string ItemPath, int Amount)? ResolveHit(string hitActorPath) {
        if (string.IsNullOrEmpty(hitActorPath)) return null;

        // The path is Package.Level.ActorName - only the last segment is the placed actor.
        var actorName = hitActorPath[(hitActorPath.LastIndexOf('.') + 1)..];
        var stem = Stem(actorName);
        if (stem.Length == 0) return null;

        if (!StemYields.TryGetValue(stem, out var yield)) {
            // Not an error - most things are not harvestable. Logged once per stem, capped, because
            // the list of stems that SHOULD have resolved is the only way a gap in the generated
            // table ever becomes visible.
            if (UnknownStemsSeen.Add(stem) && UnknownStemsSeen.Count <= 40) {
                Console.WriteLine($"FortHarvestResources: '{stem}' yields no resource (not in the generated table)");
            }

            return null;
        }

        // "Wood|Medium|ResourceWoodMedium" - resource, amount tier, and the exact curve-table row
        // name Tools/HarvestTable voted for this stem. Older entries (before pass 3 existed) may
        // still be two-part; tier alone is what those fall back to via AmountFor.
        var parts = yield.Split('|', 3);
        var resource = parts[0];
        var tier = parts.Length > 1 ? parts[1] : "Medium";
        var rowName = parts.Length > 2 ? parts[2] : string.Empty;

        if (!ItemPaths.TryGetValue(resource, out var itemPath)) return null;

        return (itemPath, AmountFor(tier, rowName));
    }

    /// <summary>
    ///     Adds the resource to the player's inventory, stacking onto what is already there.
    ///
    ///     Stacking matters for more than tidiness: the client shows resources as one counter per
    ///     type, and a second WoodItemData row would replicate fine and display wrong. A stack that
    ///     is already full is left completely alone, so no replication key moves and no delta is sent
    ///     for a hit that changed nothing.
    ///
    ///     This is the point where a real server would have re-traced the shot. It has not been, and
    ///     this grants on the client's word alone: a modified client can ask for resources it never
    ///     earned. Acceptable for a private server, and not for anything else.
    ///
    ///     Whatever doesn't fit in the stack (Round 47 - the stack was already full, or this hit's
    ///     amount would overflow it) is dropped on the ground as a real pickup instead of silently
    ///     discarded, via the exact same toss-in-front-of-the-player mechanism
    ///     NativeRpcHandlers.SpawnDroppedPickup already gives ServerAttemptInventoryDrop - a harvest
    ///     that fills the stack should feel the same as manually dropping the excess, not just stop
    ///     paying out.
    /// </summary>
    public static void Grant(APlayerController controller, string itemPath, int amount) {
        if (controller.WorldInventory is not { } inventory) return;

        var definition = UAssetRegistry.GetOrCreate(itemPath);
        var existing = inventory.Inventory.Items.FirstOrDefault(item => item.ItemDefinition == definition);

        if (existing == null) {
            var granted = Math.Min(amount, MaxResourceStack);
            inventory.Inventory.Add(new FFortItemEntry {
                ItemDefinition = definition,
                Count = granted
            });

            Console.WriteLine($"FortHarvestResources: granted {granted} x {definition.GetFName()} (new stack), " +
                              $"ArrayReplicationKey={inventory.Inventory.ArrayReplicationKey}");

            DropOverflow(controller, definition, amount - granted);
            return;
        }

        var room = MaxResourceStack - existing.Count;
        if (room <= 0) {
            DropOverflow(controller, definition, amount);
            return;
        }

        var toGrant = Math.Min(amount, room);
        existing.Count += toGrant;
        inventory.Inventory.MarkItemDirty(existing);

        Console.WriteLine($"FortHarvestResources: granted {toGrant} x {definition.GetFName()} -> {existing.Count}, " +
                          $"ArrayReplicationKey={inventory.Inventory.ArrayReplicationKey}");

        DropOverflow(controller, definition, amount - toGrant);
    }

    /// <summary>
    ///     The part of a harvest that didn't fit in an already-at-cap (999) stack. Spawned as an
    ///     ordinary AFortPickup via NativeRpcHandlers.SpawnDroppedPickup rather than left uncollected -
    ///     that method only needs an item definition and a count, so a bare FFortItemEntry (no guid,
    ///     no durability - nothing about a resource stack uses either) is enough to hand it.
    /// </summary>
    private static void DropOverflow(APlayerController controller, UObject definition, int amount) {
        if (amount <= 0) return;

        NativeRpcHandlers.SpawnDroppedPickup(controller, new FFortItemEntry { ItemDefinition = definition }, amount);
        Console.WriteLine($"FortHarvestResources: {definition.GetFName()} stack is full - dropped {amount} on the ground instead");
    }

    /// <summary>
    ///     "Tree_Pine_169" -> "Tree_Pine". Must stay identical to Tools/HarvestTable's own Stem() or
    ///     the generated keys stop matching what is looked up in them.
    /// </summary>
    private static string Stem(string name) =>
        System.Text.RegularExpressions.Regex.Replace(name, @"_?\d+$", "").TrimEnd('_');
}
