using AFortOnlineBeacon.Core.Objects;
using AFortOnlineBeacon.Net.Rpc;

namespace AFortOnlineBeacon.Net.Actors;

/// <summary>
///     Turns a reported hit into wood, stone or metal.
///
///     The client tells this server what it hit as an object path and nothing more:
///     ".../Sublevel_X2Y3.PersistentLevel.Tree_Pine_169". An injected server would simply ask the
///     actor (ABuildingSMActor knows its own resource type); an external one has never heard of that
///     actor and never will - it lives in a streaming sublevel this server does not load.
///
///     So the answer is baked ahead of time from the shipped maps: every placed Blueprint actor in
///     Athena joined to its class, and every class to its CDO's ResourceType and amount tier. See
///     Tools/HarvestTable, which also documents why it takes TWO properties and not one.
///
///     The generator also bakes each class's REAL MaxHealth, through the same AttributeInitKeys
///     chain the game itself walks - see <see cref="MaxHealthFor" />. That is what lets
///     <see cref="AmountForHit" /> pay the real per-hit amount instead of a full break every swing.
///
///     THE GENERATOR NOW WALKS THE SUPERSTRUCT CHAIN, and that closed the file's oldest known bug
///     twice over. A cooked Blueprint serialises only what it OVERRIDES, so a child that inherits a
///     property unchanged appears not to have it at all:
///
///       * `BuildingResourceAmountOverride` - 103 classes inherit it, and reading only leaf CDOs
///         left every one of them ABSENT from this table. That is not a missing payout, it is an
///         indestructible prop: ResolveHit doubles as the gate NativeRpcHandlers.DamageLevelActor
///         uses to decide what it may damage at all. `NeoTilted_Car12` was the reported case - a car
///         that resolved a real 400 HP through its ancestors and still could not be broken.
///       * `ResourceType` - 156 classes inherit it. The row-name fallback had been guessing for
///         them and was right all but once.
///
///     Together they fixed `Car_Pickup`, which this file blamed on inheritance from the day it was
///     written and got only half right: the missing property was the ROW, not the type. A pickup
///     truck now yields Metal|ResourceMetalMedium rather than wood.
///
///     What this deliberately does NOT do is trust the hit. The client picked the target, the
///     position and the moment; a real server re-traces all of that. Nothing here is safe against a
///     modified client, and it should not be mistaken for something that is - see <see cref="Grant"/>.
/// </summary>
internal static partial class FortHarvestResources {
    /// <summary>
    ///     The three Athena resources, as their item definitions. Ordinary path-exported assets like
    ///     every other item this server names (see UAssetRegistry): the client already has them.
    /// </summary>
    private static readonly Dictionary<string, string> ItemPaths = new(StringComparer.OrdinalIgnoreCase) {
        ["Wood"] = "/Game/Items/ResourcePickups/WoodItemData.WoodItemData",
        ["Stone"] = "/Game/Items/ResourcePickups/StoneItemData.StoneItemData",
        ["Metal"] = "/Game/Items/ResourcePickups/MetalItemData.MetalItemData"
    };

    /// <summary>
    ///     How much one hit yields, per amount tier. FALLBACK ONLY, for a row
    ///     <see cref="RowAmounts"/> (the real curve table, baked by Tools/HarvestTable's pass 3) does
    ///     not cover - every row this project has actually seen live IS covered, so this should never
    ///     fire in practice, but the tier ordering is worth keeping as a safety net against a stem
    ///     whose row name pass 3 could not resolve.
    /// </summary>
    private static readonly Dictionary<string, int> TierAmounts = new(StringComparer.OrdinalIgnoreCase) {
        ["Low"] = 2,
        ["Medium"] = 3,
        ["High"] = 5,
        ["VeryHigh"] = 7,
        ["Normal"] = 3, // LDBuildingNormal - a prefab building wall or floor
        ["Thick"] = 5   // LDBuildingThick - the same, reinforced
    };

    /// <summary>
    ///     Generated by Tools/HarvestTable's pass 3: every row of
    ///     `/Game/Balance/DataTables/ResourceRates.uasset` (a UCurveTable) evaluated at time 0 - REAL
    ///     numbers, not placeholders, read straight out of the shipped game data.
    ///
    ///     What this number does NOT mean: real Fortnite (see `ABuildingSMActor::OnDamageServer` in
    ///     PriveDev's Erbium reimplementation) does not pay this value per hit - it pays
    ///     `Eval(0) * Damage / MaxHealth`, i.e. this is a FULL-BREAK total that gets divided down by
    ///     how much of the target's health one hit actually removed. What IS exact here: the
    ///     RELATIVE proportions between rows (ResourceWoodVeryHigh really does yield ~7.6x
    ///     ResourceWoodLow, not the old TierAmounts' arbitrary 7:2), which is the part that was
    ///     previously fabricated.
    ///
    ///     THE DIVISION IS NOW POSSIBLE and <see cref="AmountForHit" /> does it: StemHealth carries
    ///     the target's real MaxHealth, so a hit pays `Eval(0) * Damage / MaxHealth` exactly as the
    ///     game does. This raw value is what a hit pays only where that health is unknown.
    /// </summary>
    private static int AmountFor(string tier, string rowName) =>
        RowAmounts.TryGetValue(rowName, out var real)
            ? Math.Max(1, (int) MathF.Round(real))
            : TierAmounts.GetValueOrDefault(tier, 3);

    /// <summary>Fortnite's per-resource stack cap.</summary>
    private const int MaxResourceStack = 999;

    private static readonly System.Collections.Concurrent.ConcurrentDictionary<string, byte> UnknownStemsSeen = new(StringComparer.OrdinalIgnoreCase);

    /// <summary>
    ///     Resolves a hit actor's path to the resource it yields, or null if it yields none - which
    ///     is most of the world: terrain, roads, and anything with no BuildingResourceAmountOverride
    ///     at all.
    /// </summary>
    public static (string ItemPath, int Amount)? ResolveHit(string hitActorPath) {
        if (Resolve(hitActorPath) is not { } resolved) return null;

        return (resolved.ItemPath, AmountFor(resolved.Tier, resolved.RowName));
    }

    /// <summary>
    ///     The target's REAL MaxHealth, or null for a stem the bake could not resolve one for.
    ///
    ///     Baked by Tools/HarvestTable's pass 2b out of the class's AttributeInitKeys and the GAS
    ///     attribute-defaults tables named in DefaultGame.ini - the same chain the game itself
    ///     walks, and the same one FortBuildingAttributes uses for player-built pieces. Map props
    ///     resolve in a DIFFERENT table from player builds (AttributesBuildingProps rather than
    ///     AthenaAttributesBuildingSection), which is why solving one did not solve the other.
    ///
    ///     Spot values, all matching real Battle Royale: a tree is 300 - six swings of a 50-damage
    ///     pickaxe - a rock 180, a car 400, a chest 500.
    /// </summary>
    public static int? MaxHealthFor(string hitActorPath) {
        if (string.IsNullOrEmpty(hitActorPath)) return null;

        var stem = Stem(hitActorPath[(hitActorPath.LastIndexOf('.') + 1)..]);
        if (stem.Length == 0) return null;

        return StemHealth.TryGetValue(stem, out var health) ? health : null;
    }

    /// <summary>
    ///     What ONE hit pays, the way the real server computes it:
    ///
    ///         Eval(0) * Damage / MaxHealth
    ///
    ///     i.e. the curve row's full-break total, scaled by the fraction of the target's health this
    ///     hit actually removed (Erbium's ABuildingSMActor::OnDamageServer, and the formula
    ///     RowAmounts' doc comment has described as unreachable ever since it was baked).
    ///
    ///     THIS HAD TO ARRIVE WITH THE REAL HEALTH, not after it. The old model paid the full-break
    ///     amount on EVERY hit, which was roughly right only because every prop shared a 200 HP
    ///     default and died in four. Giving a tree its real 300 HP without this would have paid six
    ///     full trees' worth of wood for one tree.
    ///
    ///     Returns null when the health is unknown, and the caller keeps the old flat model for that
    ///     stem rather than guessing - the two must not be mixed.
    /// </summary>
    public static int? AmountForHit(string hitActorPath, int damage) {
        if (damage <= 0) return null;
        if (Resolve(hitActorPath) is not { } resolved) return null;
        if (MaxHealthFor(hitActorPath) is not { } maxHealth || maxHealth <= 0) return null;

        var fullBreak = RowAmounts.TryGetValue(resolved.RowName, out var real)
            ? real
            : TierAmounts.GetValueOrDefault(resolved.Tier, 3);

        // At least 1: a chip that removes a measurable slice of a big prop still pays something, the
        // same floor AmountFor has always applied.
        return Math.Max(1, (int) MathF.Round(fullBreak * damage / maxHealth));
    }

    /// <summary>The stem lookup both public entry points share, so they can never disagree about what was hit.</summary>
    private static (string ItemPath, string Tier, string RowName)? Resolve(string hitActorPath) {
        if (string.IsNullOrEmpty(hitActorPath)) return null;

        // The path is Package.Level.ActorName - only the last segment is the placed actor.
        var actorName = hitActorPath[(hitActorPath.LastIndexOf('.') + 1)..];
        var stem = Stem(actorName);
        if (stem.Length == 0) return null;

        if (!StemYields.TryGetValue(stem, out var yield)) {
            // Not an error - most things are not harvestable. Logged once per stem, capped, because
            // the list of stems that SHOULD have resolved is the only way a gap in the generated
            // table ever becomes visible.
            if (UnknownStemsSeen.TryAdd(stem, 0) && UnknownStemsSeen.Count <= 40) {
                Console.WriteLine($"FortHarvestResources: '{stem}' yields no resource (not in the generated table)");
            }

            return null;
        }

        // "Wood|Medium|ResourceWoodMedium" - resource, amount tier, and the exact curve-table row
        // name Tools/HarvestTable voted for this stem. Older entries (before pass 3 existed) may
        // still be two-part; tier alone is what those fall back to via AmountFor.
        var parts = yield.Split('|', 3);
        var resource = parts[0];
        var tier = parts.Length > 1 ? parts[1] : "Medium";
        var rowName = parts.Length > 2 ? parts[2] : string.Empty;

        if (!ItemPaths.TryGetValue(resource, out var itemPath)) return null;

        return (itemPath, tier, rowName);
    }

    /// <summary>
    ///     Adds the resource to the player's inventory, stacking onto what is already there.
    ///
    ///     Stacking matters for more than tidiness: the client shows resources as one counter per
    ///     type, and a second WoodItemData row would replicate fine and display wrong. A stack that
    ///     is already full is left completely alone, so no replication key moves and no delta is sent
    ///     for a hit that changed nothing.
    ///
    ///     This is the point where a real server would have re-traced the shot. It has not been, and
    ///     this grants on the client's word alone: a modified client can ask for resources it never
    ///     earned. Acceptable for a private server, and not for anything else.
    ///
    ///     Whatever doesn't fit in the stack (Round 47 - the stack was already full, or this hit's
    ///     amount would overflow it) is dropped on the ground as a real pickup instead of silently
    ///     discarded, via the exact same toss-in-front-of-the-player mechanism
    ///     NativeRpcHandlers.SpawnDroppedPickup already gives ServerAttemptInventoryDrop - a harvest
    ///     that fills the stack should feel the same as manually dropping the excess, not just stop
    ///     paying out.
    /// </summary>
    public static void Grant(APlayerController controller, string itemPath, int amount) {
        if (controller.WorldInventory is not { } inventory) return;

        var definition = UAssetRegistry.GetOrCreate(itemPath);

        // THE SAME FILLING RULE EVERY OTHER ITEM GETS. This used to be its own copy of stacking with
        // 999 hardcoded, which was right for wood, stone and metal and for nothing else - and it was
        // the only place in the server that stacked at all, so pickups did not. FortItemStacks reads
        // the cap from the item definition itself (999 for all three resources, as it happens).
        var leftOver = FortItemStacks.Give(inventory, new FFortItemEntry { ItemDefinition = definition }, amount);

        Console.WriteLine($"FortHarvestResources: granted {amount - leftOver} x {definition.GetFName()}, " +
                          $"ArrayReplicationKey={inventory.Inventory.ArrayReplicationKey}");

        DropOverflow(controller, definition, leftOver);
    }

    /// <summary>
    ///     The part of a harvest that didn't fit in an already-at-cap (999) stack. Spawned as an
    ///     ordinary AFortPickup via NativeRpcHandlers.SpawnDroppedPickup rather than left uncollected -
    ///     that method only needs an item definition and a count, so a bare FFortItemEntry (no guid,
    ///     no durability - nothing about a resource stack uses either) is enough to hand it.
    /// </summary>
    private static void DropOverflow(APlayerController controller, UObject definition, int amount) {
        if (amount <= 0) return;

        NativeRpcHandlers.SpawnDroppedPickup(controller, new FFortItemEntry { ItemDefinition = definition }, amount);
        Console.WriteLine($"FortHarvestResources: {definition.GetFName()} stack is full - dropped {amount} on the ground instead");
    }

    /// <summary>
    ///     "Tree_Pine_169" -> "Tree_Pine". Must stay identical to Tools/HarvestTable's own Stem() or
    ///     the generated keys stop matching what is looked up in them.
    /// </summary>
    private static string Stem(string name) =>
        System.Text.RegularExpressions.Regex.Replace(name, @"_?\d+$", "").TrimEnd('_');
}
