#!/usr/bin/env python
"""Bake every weapon's REAL damage numbers into a C# table, so a hit stops being worth a flat 20.

WHY THIS EXISTS. `FortDamageSystem.WeaponDamage` is 20 for everything - a pickaxe, a sniper rifle and
a point-blank shotgun pellet all take exactly the same amount off a player - and
`NativeRpcHandlers.BuildingDamagePerHit` is the same placeholder on the structure side. The real
numbers are per weapon, they are not on the item, and they are not one number each:

    Assault_Auto_Athena_SR_Ore_T03   36.0 at 5000uu falling to 24.3 by 10000uu, x2.0 on a crit
    Shotgun_Standard_Athena_UC_T03    9.5 PER PELLET at 640uu, down to 1.0 at 3072uu
    Harvest_Pickaxe_Athena_C_T01     20.0 flat to a player, 50.0 to a structure

WHERE THEY LIVE, and why it takes a join. `WeaponStatHandle` on the item definition is a
DataTableRowHandle; its RowName names a row and its DataTable says WHICH table - `AthenaRangedWeapons`
for 97 of the 98 weapons and `AthenaMeleeWeapons` for the pickaxe. THAT row carries the damage.

THE FALLOFF IS FOUR BREAKPOINTS, not a single number: (RngPB, DmgPB), (RngMid, DmgMid),
(RngLong, DmgLong), (RngMax, DmgMaxRange), with a separate EnvDmg* set for structures. A melee row
has all four ranges at 0, which the runtime reads as "flat" - see FortWeaponStats.DamageAt.

DamageZone_Critical is the headshot multiplier (2.0 on most guns, 1.0 on the pickaxe) and
DamageZone_Vulnerability is the structural weak-spot one (10.0 on the pickaxe) - the server has been
guessing 3 for that.

Same shape as Tools/ProjectileTable and Tools/HarvestTable: pakreader dumps, this emits, the server
compiles the answer in. See PriveDev/docs/PORTING-TO-ANOTHER-VERSION.md.

INPUT, from Tools/PakReader (which needs FORTNITE_PAKS and FORTNITE_AES_KEY):

    pakreader find "Athena/Items/Weapons/WID_"                     # -> a list of item paths
    pakreader weaponstats <fileOfItemPaths> > wstats.txt           # path<TAB>row<TAB>table<TAB>...
    pakreader rows FortniteGame/Content/Athena/Items/Weapons/AthenaRangedWeapons "" 400000 > ranged.json
    pakreader rows FortniteGame/Content/Athena/Items/Weapons/AthenaMeleeWeapons  "" 400000 > melee.json

    python gen_weapon_stats.py <wstats.txt> <ranged.json> <melee.json> <output.cs>
"""
import json
import sys

# (C# field, row column). Order is the order they are emitted in, which is only cosmetic - unlike
# Tools/VehicleSeats, nothing here is a wire format.
FIELDS = [
    ('RngPB', 'RngPB'), ('RngMid', 'RngMid'), ('RngLong', 'RngLong'), ('RngMax', 'RngMax'),
    ('DmgPB', 'DmgPB'), ('DmgMid', 'DmgMid'), ('DmgLong', 'DmgLong'), ('DmgMax', 'DmgMaxRange'),
    ('EnvPB', 'EnvDmgPB'), ('EnvMid', 'EnvDmgMid'), ('EnvLong', 'EnvDmgLong'), ('EnvMax', 'EnvDmgMaxRange'),
    ('Critical', 'DamageZone_Critical'), ('Vulnerability', 'DamageZone_Vulnerability'),

    # Not damage, but from the same row and needed by the same feature: firing has never spent a
    # round on this server (reloading works, the magazine just never went down).
    ('AmmoPerFire', 'AmmoCostPerFire'), ('CartridgesPerFire', 'CartridgePerFire'),
    ('ReloadTime', 'ReloadTime'), ('ClipSize', 'ClipSize'),
]


def load_rows(path):
    table = json.load(open(path, encoding='utf-8'))
    return table.get('Rows') or table['Properties']['Rows']


def main():
    if len(sys.argv) < 5:
        print(__doc__)
        return 2

    tables = {
        'AthenaRangedWeapons': load_rows(sys.argv[2]),
        'AthenaMeleeWeapons': load_rows(sys.argv[3]),
    }

    weapons = []
    missing = []

    for line in open(sys.argv[1], encoding='utf-8'):
        parts = line.rstrip('\n').split('\t')
        if len(parts) < 3:
            continue

        path, row, table = parts[0], parts[1], parts[2]

        # "/Game/.../WID_Assault_AutoHigh_Athena_SR_Ore_T03" -> the bare name, which is what the
        # server has at damage time (the held weapon's WeaponData FName). The `.Name` suffix of a
        # full OBJECT path is stripped too: pakreader accepts both spellings, and a table keyed
        # "WID_X.WID_X" matches nothing at runtime while looking perfectly correct in the file.
        name = path.rsplit('/', 1)[-1].split('.', 1)[0]

        stats = tables.get(table, {}).get(row)
        if stats is None:
            missing.append(f'{name} -> {table}:{row}')
            continue

        weapons.append((name, row, [float(stats.get(column, 0.0)) for _, column in FIELDS]))

    weapons.sort()

    with open(sys.argv[4], 'w', encoding='utf-8') as out:
        out.write('// <auto-generated> Tools/WeaponStats/gen_weapon_stats.py - do not edit by hand.\n')
        out.write('//\n')
        out.write("// Each weapon's own damage, joined from its WeaponStatHandle row in\n")
        out.write('// AthenaRangedWeapons / AthenaMeleeWeapons. Four range breakpoints per damage kind\n')
        out.write('// (player and structure), plus the crit and weak-spot multipliers. The stat ROW name is\n')
        out.write('// kept in the comment because several weapon tiers share numbers and because a\n')
        out.write('// surprising value is nearly always the right value for the row it really points at.\n')
        out.write('\n')
        out.write('namespace AFortOnlineBeacon.Net.Actors;\n\n')
        out.write('internal static partial class FortWeaponStats {\n')
        out.write(f'    /// <summary>{len(weapons)} weapons, by item definition name.</summary>\n')
        out.write('    private static readonly Dictionary<string, FWeaponStats> Stats =\n')
        out.write('        new(StringComparer.OrdinalIgnoreCase) {\n')

        for name, row, values in weapons:
            fields = ', '.join(f'{field} = {value:g}f' for (field, _), value in zip(FIELDS, values))
            out.write(f'            ["{name}"] = new() {{ {fields} }},   // {row}\n')

        out.write('        };\n')
        out.write('}\n')

    print(f'{len(weapons)} weapon(s) -> {sys.argv[4]}')
    if missing:
        print(f'  rows not found ({len(missing)}), left to the fallback: ' + ', '.join(missing))
    return 0


if __name__ == '__main__':
    sys.exit(main())
