#!/usr/bin/env python
"""Bake Fortnite 10.40's authored building connectivity into C#.

Input:  Tools/PakReader `connectivity` output (see PriveDev/dumpwork/connectivity.txt).
Output: AFortOnlineBeacon/Net/Actors/FortBuildingConnectivity.Generated.cs

    gen_connectivity.py <connectivity.txt> <out.cs>
"""
import sys, re

FACES = ["Front", "Left", "Back", "Right", "Upper", "Lower"]

def main():
    src, out = sys.argv[1], sys.argv[2]
    masks, users, order = {}, {}, []

    for line in open(src, encoding="utf-8"):
        line = line.rstrip("\n")
        if line.startswith("#"):
            m = re.match(r"# (\S+)\s+\[[^\]]*\]\s+used by: (.*)", line)
            if m and m.group(2) != "(none)":
                users[m.group(1)] = [c.replace("Default__", "") for c in m.group(2).split(",")]
            continue
        if "\t" not in line:
            continue
        name, face, bits = line.split("\t")
        if name not in masks:
            masks[name] = {}
            order.append(name)
        # Bit q of row r is index r*5+q, packed LSB-first into a 25-bit uint.
        masks[name][face] = sum(1 << i for i, c in enumerate(bits) if c == "1")

    with open(out, "w", encoding="utf-8-sig", newline="\n") as f:
        w = f.write
        w("""// <auto-generated> Tools/Connectivity/gen_connectivity.py over Tools/PakReader `connectivity` - do not edit by hand.
//
// Fortnite 10.40's REAL building connectivity, authored per edit-mode pattern.
//
// This is not a geometric approximation. UBuildingStructuralSupportSystem::AreNeighborsConnected
// (impl 0x141413B60 in the 10.40 client, see the afortonlinebeacon-status memory Round 71) reduces to
// counting overlapping bits between two pieces' masks and testing `>= 2` - literally `cmp eax, 2 /
// setge`. The masks themselves are not in the code at all: each building class points at an
// EditModePatternData asset (UBuildingEditModeMetadata) whose ConnectivityCubeData holds them, which
// is why every attempt to derive connectivity from geometry came out subtly wrong.
//
// LAYOUT, established by comparing asymmetric patterns rather than assumed:
//
//   Six faces - Front, Left, Back, Right, Upper, Lower - each a 5x5 bool grid, packed LSB-first as
//   bit (row * 5 + column) of a 25-bit uint.
//
//   ROW is HEIGHT and ROW 0 IS THE TOP. Proof: EMP_Wall_Solid's Front is a ring over rows 0-3;
//   EMP_Wall_HalfWallS is the same ring with row 0 removed, and EMP_Wall_QuarterWallS with rows 0-1
//   removed. The half and quarter walls also lose their Upper face entirely while keeping Lower -
//   they no longer reach the ceiling. A column-major reading cannot produce that pattern.
//
//   COLUMN is WIDTH, and MIRRORING IS A COLUMN FLIP (q -> 4 - q) ON EVERY FACE PLUS A Left<->Right
//   FACE SWAP. Proof: EMP_Wall_HalfWallHalf and EMP_Wall_HalfWallHalf_Right are exactly that
//   transform of each other, as are EMP_Wall_Brace_TopLeft and EMP_Wall_Brace_TopRight.
//
// GEOMETRY, solved from the client and then cross-checked against all 65 patterns at once:
//
//   0x141431BC0 scales a cell offset by 4 in X and Y but by 3 in Z, and refuses |offset| >= 3. So one
//   building cell is a 5 x 5 x 4 VOXEL BLOCK - x,y over 4 steps, z over 3 - and neighbouring cells
//   OVERLAP BY EXACTLY ONE LAYER on every axis. That is why a side face has 5 columns but only 4
//   usable rows, and why row 4 is empty on every side face in the shipped data while only Upper and
//   Lower ever use it.
//
//   The six masks are the surface of that block:
//
//     Front  x = 4        Back   x = 0, columns flipped
//     Left   y = 0        Right  y = 4, columns flipped
//     side faces: rows 0..3 -> z = 3 - row     (row 0 is the TOP)
//     Upper  z = 3        Lower  z = 0         (row -> y, column -> x, x flipped)
//
//   This assignment was not assumed. Every one of the block's 12 edges is described TWICE, once by
//   each of the two faces meeting there, so a wrong orientation contradicts itself. Brute-forcing all
//   393216 candidate assignments against all 65 patterns leaves exactly 8 - which are the 8 symmetries
//   of the block about the vertical axis, i.e. the answer is unique up to which world direction
//   "Front" names. The one above is the UE-conventional choice (X forward, Y right, Z up).
//
//   MIRRORING is then just y -> 4 - y, confirmed on all four shipped mirror pairs
//   (HalfWallHalf/_Right, Brace_TopLeft/_TopRight, ArchwayLarge/_Left, RoofWall_TopLeft/_TopRight).
//   YAW +90 is (x, y, z) -> (4 - y, x, z). Neither is baked in here; both are applied at runtime.
//
// The rule reproduces real behaviour, which is the check that matters: two floors side by side share
// 5 voxels and connect, two floors DIAGONALLY adjacent share exactly 1 - a single corner - and do
// not, which is precisely why the threshold is 2. A full wall shares 5 voxels with the floor of the
// cell above; a HALF wall shares 0, because it does not reach it.

namespace AFortOnlineBeacon.Net.Actors;

/// <summary>One piece's connectivity cube - six 5x5 masks, packed as described above.</summary>
internal readonly record struct FConnectivityCube(uint Front, uint Left, uint Back, uint Right, uint Upper, uint Lower);

internal static partial class FortBuildingConnectivity {
    /// <summary>Edit-mode pattern name (EMP_*) -> its cube.</summary>
    public static readonly Dictionary<string, FConnectivityCube> ByPattern = new(StringComparer.OrdinalIgnoreCase) {
""")
        for name in sorted(order, key=str.lower):
            m = masks[name]
            vals = ", ".join("0x%07Xu" % m.get(fa, 0) for fa in FACES)
            w('        ["%s"] = new(%s),\n' % (name, vals))
        w("""    };

    /// <summary>
    ///     Building class name (as it appears in the class path's last segment) -> its pattern name.
    ///     Read off each class CDO's EditModePatternData, the same property the client's own
    ///     structural system follows.
    /// </summary>
    public static readonly Dictionary<string, string> PatternByClass = new(StringComparer.OrdinalIgnoreCase) {
""")
        pairs = sorted(((c, p) for p, cs in users.items() for c in cs), key=lambda t: t[0].lower())
        for cls, pat in pairs:
            w('        ["%s"] = "%s",\n' % (cls, pat))
        w("""    };

    /// <summary>The cube for a building class, or null for a class the shipped patterns do not cover.</summary>
    public static FConnectivityCube? For(string className) =>
        PatternByClass.TryGetValue(className, out var pattern) && ByPattern.TryGetValue(pattern, out var cube)
            ? cube
            : null;
}
""")
    print("%d patterns, %d classes -> %s" % (len(order), len(pairs), out))

main()
