#!/usr/bin/env python
"""Emit FortWeaponActorClasses' table from a MapActorDump property dump of the Athena WIDs.

A weapon item definition (WID_*) is DATA, not a class: the actor the server is supposed to spawn
when that item is equipped lives in its WeaponActorClass property, e.g.

    WID_Assault_Auto_Athena_C_Ore_T02
        WeaponActorClass  /Game/Weapons/FORT_Rifles/Blueprints/Assault/B_Assault_Auto_Athena.B_Assault_Auto_Athena_C

An injected server just calls UFortWeaponItemDefinition::GetWeaponActorClass(). AFortOnlineBeacon
runs outside the game and reads no paks at runtime, so the mapping has to be baked in - which is
what this generates.

Producing the input:

    Tools/MapActorDump/bin/Debug/net10.0/MapActorDump.exe <PaksDir> <AesKeyHex> \
        FortniteGame/Content/Athena/Items/Weapons/ props:WID_ > athena_wids.txt

Usage:

    python Tools/WeaponClasses/gen_weapon_actor_classes.py athena_wids.txt \
        > AFortOnlineBeacon/Net/Actors/FortWeaponActorClasses.Generated.cs
"""
import re
import sys

HEADER = '''// GENERATED by Tools/WeaponClasses/gen_weapon_actor_classes.py - do not edit by hand.
// Source: a CUE4Parse dump of every WID_* under FortniteGame/Content/Athena/Items/Weapons in the
// 10.40 paks. See the script's docstring for the exact command.

namespace AFortOnlineBeacon.Net.Actors;

internal static partial class FortWeaponActorClasses {
    /// <summary>
    ///     Item definition name (the WID_ asset's object name, i.e. UObject.GetFName()) -> the
    ///     Blueprint class path of the AFortWeapon actor to spawn for it. %d entries.
    /// </summary>
    private static readonly Dictionary<string, string> Table = new(StringComparer.OrdinalIgnoreCase) {
'''

FOOTER = '''    };
}
'''


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        return

    with open(sys.argv[1], encoding="utf-8", errors="replace") as fh:
        lines = fh.read().split("\n")

    # The dump repeats "--- <path>" / "<ExportType>  <Name>" / indented "Prop  Value" lines. Only the
    # export whose own name starts with WID_ matters; a WeaponActorClass seen under any other export
    # would belong to something else in the same package.
    entries = {}
    current = None

    for line in lines:
        if line.startswith("--- "):
            current = None
            continue

        stripped = line.strip()
        if not line.startswith("    "):
            m = re.match(r"^\S+\s+(WID_\w+)$", stripped)
            current = m.group(1) if m else None
            continue

        if current is None:
            continue

        m = re.match(r"^WeaponActorClass\s+(\S.*)$", stripped)
        if m:
            entries[current] = m.group(1).strip()

    print(HEADER % len(entries), end="")
    for name in sorted(entries, key=str.lower):
        print('        ["%s"] = "%s",' % (name, entries[name]))
    print(FOOTER, end="")


main()
