#!/usr/bin/env python
"""Emit FortWeaponActorClasses' table from a MapActorDump property dump of the Athena WIDs.

A weapon item definition (WID_*) is DATA, not a class: the actor the server is supposed to spawn
when that item is equipped lives in its WeaponActorClass property, e.g.

    WID_Assault_Auto_Athena_C_Ore_T02
        WeaponActorClass  /Game/Weapons/FORT_Rifles/Blueprints/Assault/B_Assault_Auto_Athena.B_Assault_Auto_Athena_C

An injected server just calls UFortWeaponItemDefinition::GetWeaponActorClass(). AFortOnlineBeacon
runs outside the game and reads no paks at runtime, so the mapping has to be baked in - which is
what this generates.

Producing the input:

    Tools/MapActorDump/bin/Debug/net10.0/MapActorDump.exe <PaksDir> <AesKeyHex> \
        FortniteGame/Content/Athena/Items/Weapons/ props:WID_ > athena_wids.txt

Usage:

    python Tools/WeaponClasses/gen_weapon_actor_classes.py athena_wids.txt \
        > AFortOnlineBeacon/Net/Actors/FortWeaponActorClasses.Generated.cs
"""
import re
import sys

HEADER = '''// GENERATED by Tools/WeaponClasses/gen_weapon_actor_classes.py - do not edit by hand.
// Source: a CUE4Parse dump of every WID_* under FortniteGame/Content/Athena/Items/Weapons in the
// 10.40 paks. See the script's docstring for the exact command.

namespace AFortOnlineBeacon.Net.Actors;

internal static partial class FortWeaponActorClasses {
    /// <summary>
    ///     Item definition name (the WID_ asset's object name, i.e. UObject.GetFName()) -> the
    ///     Blueprint class path of the AFortWeapon actor to spawn for it. %d entries.
    /// </summary>
    private static readonly Dictionary<string, string> Table = new(StringComparer.OrdinalIgnoreCase) {
'''

ABILITY_HEADER = '''    /// <summary>
    ///     Item definition name -> its PrimaryFireAbility, the UGameplayAbility class the server
    ///     grants into UAbilitySystemComponent::ActivatableAbilities when the weapon is equipped.
    ///     Nothing the client can fire exists until one of these is granted. %d entries.
    /// </summary>
    private static readonly Dictionary<string, string> AbilityTable = new(StringComparer.OrdinalIgnoreCase) {
'''

AMMO_HEADER = '''    /// <summary>
    ///     Item definition name -> the FortAmmoItemDefinition its magazine draws from. Reloading
    ///     pulls from a SEPARATE inventory item, so a player holding only the weapon is correctly
    ///     told there is not enough ammo. Project-Reboot-3.0 hands out both together when a weapon
    ///     is spawned as loot (FortLootPackage.cpp:349-355, GetAmmoData + GetDropCount). %d entries.
    /// </summary>
    private static readonly Dictionary<string, string> AmmoTable = new(StringComparer.OrdinalIgnoreCase) {
'''

CLIP_HEADER = '''    /// <summary>
    ///     Item definition name -> ClipSize, i.e. how many rounds a full magazine holds. A WID does
    ///     not carry this: it carries a FDataTableRowHandle into a weapon-stats table, so this is
    ///     joined through that row name (see the script's docstring for the second dump). Only
    ///     ranged weapons appear - melee and trap definitions point at other tables and have no
    ///     magazine. %d entries.
    /// </summary>
    private static readonly Dictionary<string, int> ClipSizeTable = new(StringComparer.OrdinalIgnoreCase) {
'''

FOOTER = '''    };
}
'''


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        return

    with open(sys.argv[1], encoding="utf-8", errors="replace") as fh:
        lines = fh.read().split("\n")

    # The dump repeats "--- <path>" / "<ExportType>  <Name>" / indented "Prop  Value" lines. Only the
    # export whose own name starts with WID_ matters; a WeaponActorClass seen under any other export
    # would belong to something else in the same package.
    entries = {}
    current = None

    for line in lines:
        if line.startswith("--- "):
            current = None
            continue

        stripped = line.strip()
        if not line.startswith("    "):
            m = re.match(r"^\S+\s+(WID_\w+)$", stripped)
            current = m.group(1) if m else None
            continue

        if current is None:
            continue

        m = re.match(r"^WeaponActorClass\s+(\S.*)$", stripped)
        if m:
            entries.setdefault(current, {})["actor"] = m.group(1).strip()

        m = re.match(r"^PrimaryFireAbility\s+(\S.*)$", stripped)
        if m:
            entries.setdefault(current, {})["ability"] = m.group(1).strip()

        m = re.match(r"^AmmoData\s+(\S.*)$", stripped)
        if m:
            entries.setdefault(current, {})["ammo"] = m.group(1).strip()

        # The WeaponStatHandle's RowName, printed by MapActorDump's one level of struct recursion.
        m = re.match(r"^RowName\s+(\S+)$", stripped)
        if m:
            entries.setdefault(current, {}).setdefault("row", m.group(1))

    actors = {k: v["actor"] for k, v in entries.items() if "actor" in v}
    abilities = {k: v["ability"] for k, v in entries.items() if "ability" in v}

    print(HEADER % len(actors), end="")
    for name in sorted(actors, key=str.lower):
        print('        ["%s"] = "%s",' % (name, actors[name]))
    print("    };")
    print()
    print(ABILITY_HEADER % len(abilities), end="")
    for name in sorted(abilities, key=str.lower):
        print('        ["%s"] = "%s",' % (name, abilities[name]))
    print("    };")
    print()

    ammo = {k: v["ammo"] for k, v in entries.items() if "ammo" in v}
    print(AMMO_HEADER % len(ammo), end="")
    for name in sorted(ammo, key=str.lower):
        print('        ["%s"] = "%s",' % (name, ammo[name]))
    print("    };")
    print()

    # WID -> ClipSize, joined through the stat row name. Only ranged weapons resolve: melee and
    # trap definitions point at other tables entirely, and have no magazine to size.
    clips = {}
    if len(sys.argv) > 2:
        row_clip, row = {}, None
        with open(sys.argv[2], encoding="utf-8", errors="replace") as fh:
            for line in fh:
                stripped = line.strip()
                m = re.match(r"^DataTable row\s+(\S+)$", stripped)
                if m:
                    row = m.group(1)
                    continue
                if row:
                    m = re.match(r"^ClipSize\s+(\d+)$", stripped)
                    if m:
                        row_clip[row] = int(m.group(1))

        clips = {k: row_clip[v["row"]] for k, v in entries.items()
                 if "row" in v and v["row"] in row_clip}

    print(CLIP_HEADER % len(clips), end="")
    for name in sorted(clips, key=str.lower):
        print('        ["%s"] = %d,' % (name, clips[name]))
    print(FOOTER, end="")


main()
