#!/usr/bin/env python
"""Turn each vehicle Blueprint's OWN replicated fields into a C# table, so RPCs from a vehicle decode.

WHY THIS EXISTS. `FClassNetCache` numbers an RPC's field by walking the whole class chain, and the
index travels as a bounded int whose WIDTH is `CeilLogTwo(GetMaxIndex() + 1)`. A Blueprint vehicle
adds its own net fields on top of AFortAthenaVehicle - the shopping cart adds five - so a server that
knows only the native fields reads the index at the wrong width and every bit after it is garbage.
The symptom is a bunch that decodes as a nonsense field:

    field[1]=bCanBeDamaged on ChIndex=18 Actor=ShoppingCartVehicleSK_C (867 payload bits)

a bool property, arriving from a client, carrying 867 bits. The BP fields do not shift the native ones
(they sort after, at higher indices) - they change how many bits the number takes to send.

Same shape as Tools/NetFieldVerify's weapon chains, which exist for exactly this reason on weapons.

INPUT, from Tools/PakReader (which needs FORTNITE_PAKS and FORTNITE_AES_KEY):

    pakreader netfields <fileOfClassPaths> > vehiclefields.txt      # class<TAB>property|function<TAB>name

    python gen_vehicle_caches.py <vehiclefields.txt> <output.cs>
"""
import sys
from collections import defaultdict


def main():
    if len(sys.argv) < 3:
        print(__doc__)
        return 2

    classes = defaultdict(list)

    for line in open(sys.argv[1], encoding='utf-8'):
        parts = line.rstrip('\n').split('\t')
        if len(parts) < 3:
            continue

        # "/Game/.../ShoppingCartVehicleSK.ShoppingCartVehicleSK_C" -> "ShoppingCartVehicleSK_C",
        # which is the name the server sees on the spawned actor's class.
        classes[parts[0].rsplit('.', 1)[-1]].append(parts[2])

    with open(sys.argv[2], 'w', encoding='utf-8') as out:
        out.write('// <auto-generated> Tools/VehicleNetCaches/gen_vehicle_caches.py - do not edit by hand.\n')
        out.write('//\n')
        out.write("// Each vehicle Blueprint's OWN replicated fields - properties and RPCs together, which is how\n")
        out.write('// UClass::SetUpRuntimeReplicationData builds NetFields (one list, sorted by name).\n')
        out.write('//\n')
        out.write('// A vehicle whose Blueprint adds nothing is ABSENT rather than listed empty; the runtime side\n')
        out.write('// treats "not in the table" as "adds no fields", which is the same answer and one fewer entry.\n')
        out.write('\n')
        out.write('namespace AFortOnlineBeacon.Net;\n\n')
        out.write('internal static partial class FortVehicleNetCaches {\n')
        out.write(f'    /// <summary>{len(classes)} vehicle Blueprints that add fields of their own.</summary>\n')
        out.write('    private static readonly Dictionary<string, string[]> OwnFields =\n')
        out.write('        new(StringComparer.OrdinalIgnoreCase) {\n')

        for name in sorted(classes):
            fields = ', '.join(f'"{f}"' for f in sorted(classes[name], key=str.lower))
            out.write(f'            ["{name}"] = new[] {{ {fields} }},\n')

        out.write('        };\n')
        out.write('}\n')

    print(f'{len(classes)} vehicle Blueprint(s) -> {sys.argv[2]}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
