#!/usr/bin/env python
"""Emit FortEmoteAssets.Generated.cs - the emote properties that live inside the .uasset.

WHY THIS EXISTS. Emoting itself has worked and been live-confirmed for a while (see the
emote-wire-flow memory: grant GAB_Emote_Generic's CDO with the emote asset as SourceObject, then
ClientActivateAbilitySucceed with a server-initiated key). Everything still MISSING from it had one
single root cause - the value is inside the cooked asset, and a server running outside the game
cannot read one:

  * Toys are refused outright, because their ability is UAthenaToyItemDefinition::ToySpawnAbility
    and there is no generic toy ability to fall back on.
  * Moving emotes dance on the spot: bMovingEmote / bMoveForwardOnly / WalkForwardSpeed are wire
    handles 52/53/71 on the pawn, already Reserved and correctly numbered, waiting for values.
  * Emotes with a bespoke ability get the generic one instead - UAthenaDanceItemDefinition::CustomDanceAbility.

The paks are open now, so all three are simply readable. This is the same bake-it pattern as
Tools/HarvestTable, Tools/WeaponClasses and Tools/ConsumableTable.

CLASSIFICATION COMES FROM THE ASSET, NOT THE FOLDER. FortEmoteSystem currently decides "dance vs
spray vs toy" by looking for /Sprays/ or /Toys/ in the path, because the class was not on the wire
and could not be read. Each definition's real UClass is in these dumps, so that guess can go.

Note how few emotes carry these properties at all: of 263 dances, 22 set bMovingEmote, 21
bMoveForwardOnly, 29 WalkForwardSpeed and 3 CustomDanceAbility. A cooked asset omits default-valued
properties, so an emote that is absent from a table below genuinely has that default - it is not
missing data.

Producing the inputs (three folders, three classes):

    dotnet run --project Tools/MapActorDump -- <PaksDir> <AesKeyHex> \
        FortniteGame/Content/Athena/Items/Cosmetics/Dances/ props:EID_  > emote_defs.txt
    dotnet run --project Tools/MapActorDump -- <PaksDir> <AesKeyHex> \
        FortniteGame/Content/Athena/Items/Cosmetics/Sprays/ props:SPID_ > spray_defs.txt
    dotnet run --project Tools/MapActorDump -- <PaksDir> <AesKeyHex> \
        FortniteGame/Content/Athena/Items/Cosmetics/Toys/ props:TOY_    > toy_defs.txt

Usage:

    python Tools/EmoteTable/gen_emotes.py emote_defs.txt spray_defs.txt toy_defs.txt \
        > AFortOnlineBeacon/Net/Actors/FortEmoteAssets.Generated.cs
"""
import re
import sys


def parse_exports(path):
    """MapActorDump's props: output -> [(class_name, export_name, {prop: value})], package included."""
    exports = []
    current = None
    package = None

    for raw in open(path, encoding="utf-8", errors="replace"):
        line = raw.rstrip("\n")
        if not line.strip():
            continue

        if line.startswith("--- "):
            package = line[4:].strip()
            if package.endswith(".uasset"):
                package = package[: -len(".uasset")]
            if package.startswith("FortniteGame/Content/"):
                package = "/Game/" + package[len("FortniteGame/Content/"):]
            continue

        if not line.startswith(" "):
            parts = re.split(r"\s{2,}", line.strip())
            if len(parts) == 2:
                current = (parts[0], parts[1], {"__package": package})
                exports.append(current)
            continue

        if current is None:
            continue

        indent = (len(line) - len(line.lstrip(" "))) // 4
        if indent != 1:
            continue

        parts = re.split(r"\s{2,}", line.strip(), maxsplit=1)
        if len(parts) == 2:
            current[2][parts[0]] = parts[1].strip()

    return exports


def soft_path(value):
    """Strip CUE4Parse decoration, leaving the /Game/... path."""
    if not value:
        return None
    match = re.search(r"'([^']+)'", value)
    if match:
        inner = match.group(1)
        return "/Game/" + inner[len("FortniteGame/Content/"):] if inner.startswith("FortniteGame/Content/") else inner
    return value if value.startswith("/") else None


HEADER = '''// GENERATED by Tools/EmoteTable/gen_emotes.py - do not edit by hand.
// Source: the 10.40 paks, three CUE4Parse dumps of Athena/Items/Cosmetics/{Dances,Sprays,Toys}.
// See the script's docstring for the exact commands.

namespace AFortOnlineBeacon.Net.Actors;

/// <summary>
///     The emote properties that live inside the cooked asset, which a server running outside the
///     game cannot read at runtime - so they are baked in, the same way harvest yields, weapon actor
///     classes and consumable amounts are.
///
///     Emoting already worked; these are the three things it could not do without asset values:
///     spawn a TOY (ToySpawnAbility), MOVE while dancing (bMovingEmote / bMoveForwardOnly /
///     WalkForwardSpeed, pawn wire handles 52/53/71), and use an emote's OWN ability rather than the
///     generic one (CustomDanceAbility).
///
///     A cooked asset omits default-valued properties, so an emote missing from a table here has
///     that property's default - absence is data, not a gap. Only %(moving)d of %(dances)d dances
///     move at all.
/// </summary>
internal static class FortEmoteAssets {
    /// <summary>Which kind of "emote" an item definition is - read from its real UClass, not guessed from its folder.</summary>
    internal enum EEmoteKind { Dance, Spray, Toy }

    /// <summary>
    ///     One emote's asset-side properties. Everything optional is null/NaN when the cooked asset
    ///     left it at its default.
    /// </summary>
    internal readonly record struct FEmoteAsset(
        EEmoteKind Kind,
        string DisplayName,
        bool bMovingEmote,
        bool bMoveForwardOnly,
        float WalkForwardSpeed,
        string? CustomAbility);

'''


def emit(dances, sprays, toys):
    entries = {}
    moving = 0

    for kind, exports in (("Dance", dances), ("Spray", sprays), ("Toy", toys)):
        for cls, name, props in exports:
            if not cls.endswith("ItemDefinition"):
                continue

            is_moving = props.get("bMovingEmote") == "True"
            moving += 1 if (kind == "Dance" and is_moving) else 0

            # A toy's ability is its ToySpawnAbility; a dance's is CustomDanceAbility when it has
            # one. Both land in the same field because the runtime asks the same question of both:
            # "is there an ability of your own to grant instead of the generic one?"
            ability = soft_path(props.get("ToySpawnAbility") or props.get("CustomDanceAbility"))

            speed = props.get("WalkForwardSpeed")
            entries[name] = (
                kind,
                props.get("DisplayName", name).replace('"', "'"),
                is_moving,
                props.get("bMoveForwardOnly") == "True",
                float(speed) if speed else None,
                ability,
                f'{props["__package"]}.{name}',
            )

    out = [HEADER % {"moving": moving, "dances": sum(1 for c, _, _ in dances if c.endswith("ItemDefinition"))}]

    out.append(f"    /// <summary>Item definition name -> its asset-side properties. {len(entries)} entries.</summary>\n")
    out.append("    private static readonly Dictionary<string, FEmoteAsset> Assets = "
               "new(StringComparer.OrdinalIgnoreCase) {\n")
    for name in sorted(entries):
        kind, display, is_moving, forward_only, speed, ability, _path = entries[name]
        speed_text = "float.NaN" if speed is None else f"{speed:g}f"
        ability_text = "null" if ability is None else f'"{ability}"'
        out.append(f'        ["{name}"] = new(EEmoteKind.{kind}, "{display}", '
                   f'{str(is_moving).lower()}, {str(forward_only).lower()}, {speed_text}, {ability_text}),\n')
    out.append("    };\n\n")

    out.append('''    public static FEmoteAsset? For(string itemDefinitionName) =>
        Assets.TryGetValue(itemDefinitionName, out var asset) ? asset : null;

    /// <summary>
    ///     The emote's own ability class path, or null to use the generic one. Toys ALWAYS have one -
    ///     there is no generic toy ability, which is why toys were refused outright before this table.
    /// </summary>
    public static string? AbilityFor(string itemDefinitionName) =>
        Assets.TryGetValue(itemDefinitionName, out var asset) ? asset.CustomAbility : null;
}
''')
    return "".join(out)


def main():
    if len(sys.argv) < 4:
        sys.exit(__doc__)

    sys.stdout.write(emit(parse_exports(sys.argv[1]), parse_exports(sys.argv[2]), parse_exports(sys.argv[3])))


if __name__ == "__main__":
    main()
