#!/usr/bin/env python
"""Turn Fortnite's real loot tables into a C# table the server can roll against.

WHY A GENERATOR. Same reason as Tools/HarvestTable and Tools/RepHandles: the source data is 60 GB of
paks, the answer is a few hundred rows, and the server should carry the answer rather than the paks.
See PriveDev/docs/PORTING-TO-ANOTHER-VERSION.md section 3.1.

INPUT - produced by Tools/PakReader, which needs FORTNITE_PAKS and FORTNITE_AES_KEY:

    pakreader rows FortniteGame/Content/Items/Datatables/AthenaLootTierData_Client > AthenaLootTierData.json
    pakreader rows FortniteGame/Content/Items/Datatables/AthenaLootPackages_Client > AthenaLootPackages.json

HOW FORTNITE'S LOOT ACTUALLY WORKS, which is what this preserves:

  1. A container names a TIER GROUP ("Loot_AthenaTreasure"). Its rows are weighted; pick one.
  2. That row names a LOOT PACKAGE id and a NumLootPackageDrops, plus per-CATEGORY weights and
     min/max counts. Categories are how a chest reliably gives you a gun AND ammo AND a consumable
     rather than four guns.
  3. Every package row sharing that id belongs to it, each tagged with its category. Within a
     category, pick by weight.
  4. A picked row either carries an ItemDefinition (a leaf - that is the item) or a LootPackageCall
     naming ANOTHER package group, which is rolled the same way. That recursion is why the tables are
     1486 rows: the shared "which SMG, at which rarity" list is written once and called from
     everywhere.

Only groups reachable from the roots below are emitted, transitively - the full table is mostly
event/LTM content this server has no use for.

    python gen_loot.py <dumpwork-dir> <output.cs>
"""
import json
import os
import sys

# The containers this server actually has. Everything else in the table is an LTM, a vending machine,
# or a season-specific event.
ROOT_TIER_GROUPS = [
    "Loot_AthenaTreasure",     # chests
    "Loot_AthenaFloorLoot",    # floor loot
    "Loot_AthenaAmmoLarge",    # ammo boxes
    "Loot_AthenaAmmoSmall",
    "Loot_AthenaSupplyDrop",   # supply drops, for when those exist
    # Supply llamas. The name is not a guess - AthenaSupplyDrop_Llama_C's CDO carries
    # `LootTableName = Loot_AthenaLlama` (pakreader props on the Blueprint).
    "Loot_AthenaLlama",
]


def load(path):
    with open(path, encoding="utf-8") as f:
        return json.load(f)["Rows"]


def item_path(entry):
    """The leaf item, as the '/Game/....Name' path UAssetRegistry wants, or None for a call row."""
    definition = entry.get("ItemDefinition") or {}
    name = definition.get("AssetPathName") or "None"
    return None if name in ("None", "") else name


def main():
    dump_dir = sys.argv[1] if len(sys.argv) > 1 else r"C:\Users\user\Documents\PriveDev\dumpwork"
    out_path = sys.argv[2] if len(sys.argv) > 2 else "FortLootTables.Generated.cs"

    tiers = load(os.path.join(dump_dir, "AthenaLootTierData.json"))
    packages = load(os.path.join(dump_dir, "AthenaLootPackages.json"))

    # packageId -> [rows], the grouping the runtime rolls within.
    by_package = {}
    for row in packages.values():
        by_package.setdefault(row["LootPackageID"], []).append(row)

    # Walk from the roots so only reachable packages are emitted.
    wanted, queue = set(), []
    tier_rows = []
    for row in tiers.values():
        if row["TierGroup"] not in ROOT_TIER_GROUPS:
            continue
        tier_rows.append(row)
        queue.append(row["LootPackage"])

    while queue:
        pkg = queue.pop()
        if pkg in wanted or pkg not in by_package:
            continue
        wanted.add(pkg)
        for row in by_package[pkg]:
            call = row.get("LootPackageCall") or "None"
            if call != "None":
                queue.append(call)

    lines = []
    w = lines.append
    w("// <auto-generated> Tools/LootTable/gen_loot.py - do not edit by hand.")
    w("//")
    w("// Fortnite 10.40's own loot tables, read out of the shipped paks:")
    w("//   FortniteGame/Content/Items/Datatables/AthenaLootTierData_Client")
    w("//   FortniteGame/Content/Items/Datatables/AthenaLootPackages_Client")
    w("//")
    w("// See gen_loot.py for how the two stages fit together, and")
    w("// PriveDev/docs/PORTING-TO-ANOTHER-VERSION.md for regenerating this on another version.")
    w("")
    w("namespace AFortOnlineBeacon.Net.Actors;")
    w("")
    w("internal static partial class FortLootTables {")

    w("    /// <summary>Tier rows, grouped by the tier group a container names. Weighted.</summary>")
    w("    public static readonly Dictionary<string, FLootTierRow[]> TierGroups = new(StringComparer.OrdinalIgnoreCase) {")
    for group in ROOT_TIER_GROUPS:
        rows = [r for r in tier_rows if r["TierGroup"] == group]
        if not rows:
            continue
        w(f'        ["{group}"] = new FLootTierRow[] {{')
        for r in rows:
            weights = ", ".join(str(int(v)) for v in r["LootPackageCategoryWeightArray"])
            mins = ", ".join(str(int(v)) for v in r["LootPackageCategoryMinArray"])
            maxs = ", ".join(str(int(v)) for v in r["LootPackageCategoryMaxArray"])
            w(f'            new({r["Weight"]}f, "{r["LootPackage"]}", {r["NumLootPackageDrops"]}f,')
            w(f'                new[] {{ {weights} }}, new[] {{ {mins} }}, new[] {{ {maxs} }}),')
        w("        },")
    w("    };")
    w("")

    w("    /// <summary>Package rows by package id. A row is either a leaf item or a call into another package.</summary>")
    w("    public static readonly Dictionary<string, FLootPackageRow[]> Packages = new(StringComparer.OrdinalIgnoreCase) {")
    for pkg in sorted(wanted):
        rows = by_package[pkg]
        w(f'        ["{pkg}"] = new FLootPackageRow[] {{')
        for r in rows:
            call = r.get("LootPackageCall") or "None"
            call_cs = "null" if call == "None" else f'"{call}"'
            item = item_path(r)
            item_cs = "null" if item is None else f'"{item}"'
            w(f'            new({r["Weight"]}f, {int(r["Count"])}, {int(r["LootPackageCategory"])}, {call_cs}, {item_cs}),')
        w("        },")
    w("    };")
    w("}")

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    print(f"{len(tier_rows)} tier rows in {len(ROOT_TIER_GROUPS)} groups, {len(wanted)} packages -> {out_path}")


if __name__ == "__main__":
    main()
