#!/usr/bin/env python
"""Turn each thrown item's REAL damage numbers into a C# table the projectile system can use.

WHY THIS EXISTS. Every thrown consumable was exploding for the FRAG GRENADE's numbers - 100 to a
player and 375 to a building - because that is the one ability whose values had been read out of the
paks. So a shockwave grenade killed outright, a stink bomb killed outright, and so did a bush, a dog
sweater and every Playset grenade in the game. The real numbers are per item and they are not small
adjustments:

    Athena_Grenade       100 / 375        Athena_C4            72 / 800
    Athena_KnockGrenade    5 /   5        Athena_GasGrenade     5 /   0
    Generic_NonDamaging    0 /   0        Generic_M80          40 /   0

WHERE THEY LIVE, and why it takes a join. The item does not carry its damage: `WeaponStatHandle` is a
DataTableRowHandle naming a row in Balance/DataTables/UtilityItemDamage, and THAT row carries DmgPB
(player, point blank) and EnvDmgPB (structures). Several items share a row - every Playset grenade
points at Generic_NonDamaging - which is exactly why the table is written this way rather than as a
number per item in the assets.

Same shape as Tools/HarvestTable and Tools/StackSizes: pakreader dumps, this emits, the server
compiles the answer in. See PriveDev/docs/PORTING-TO-ANOTHER-VERSION.md.

INPUT, from Tools/PakReader (which needs FORTNITE_PAKS and FORTNITE_AES_KEY):

    pakreader weaponstats <fileOfItemPaths> > weaponstats.txt
    pakreader rows FortniteGame/Content/Balance/DataTables/UtilityItemDamage "" 200000 > utility.json

    python gen_projectiles.py <weaponstats.txt> <utility.json> <output.cs>
"""
import json
import sys


def main():
    if len(sys.argv) < 4:
        print(__doc__)
        return 2

    table = json.load(open(sys.argv[2], encoding='utf-8'))
    rows = table.get('Rows') or table['Properties']['Rows']

    items = []
    missing = set()

    for line in open(sys.argv[1], encoding='utf-8'):
        parts = line.rstrip('\n').split('\t')
        if len(parts) < 2:
            continue

        path, row = parts[0], parts[1]

        # "/Game/.../Athena_Grenade.Athena_Grenade" -> "Athena_Grenade", which is the name the server
        # has at spawn time (the held weapon's WeaponData FName).
        name = path.rsplit('.', 1)[-1]

        stats = rows.get(row)
        if stats is None:
            missing.add(row)
            continue

        player = float(stats.get('DmgPB', 0.0))
        env = float(stats.get('EnvDmgPB', 0.0))
        items.append((name, row, player, env))

    items.sort()

    with open(sys.argv[3], 'w', encoding='utf-8') as out:
        out.write('// <auto-generated> Tools/ProjectileTable/gen_projectiles.py - do not edit by hand.\n')
        out.write('//\n')
        out.write('// Each thrown item\'s own damage, joined from its WeaponStatHandle row in\n')
        out.write('// FortniteGame/Content/Balance/DataTables/UtilityItemDamage. The row name is kept in the\n')
        out.write('// comment because several items share one, and because a wrong-looking number is nearly\n')
        out.write('// always the right number for a row this item genuinely points at.\n')
        out.write('\n')
        out.write('namespace AFortOnlineBeacon.Net.Actors;\n\n')
        out.write('internal static partial class FortProjectileStats {\n')
        out.write(f'    /// <summary>{len(items)} thrown items, by item definition name.</summary>\n')
        out.write('    private static readonly Dictionary<string, (float Player, float Environment)> Damage =\n')
        out.write('        new(StringComparer.OrdinalIgnoreCase) {\n')
        for name, row, player, env in items:
            out.write(f'            ["{name}"] = ({player:g}f, {env:g}f),   // {row}\n')
        out.write('        };\n')
        out.write('}\n')

    print(f'{len(items)} thrown item(s) -> {sys.argv[3]}')
    if missing:
        print(f'  rows not found in the table (left to the fallback): {sorted(missing)}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
