"""Bake the per-ability throw speed into FortThrowSpeeds.Generated.cs.

    pakreader grenadespeeds > grenade_speeds.txt
    python gen_throw_speeds.py [grenade_speeds.txt] [out.cs]

One constant was being used for every throw, and it was the frag grenade's 4000. That is right for
most of them and wrong where it matters: a firework mortar's own speed is 2500 and a clinger's is
6000, so one sailed off the far side of the island and the other fell short - which is what "it flies
too far" was about.

ONLY THE OVERRIDERS ARE LISTED, and that is the whole table rather than a sample: a cooked Blueprint
serialises what it CHANGES, so an ability with no GrenadeSpeedMin of its own inherits the family's
4000. Nine abilities in the entire game override it.
"""
import io
import sys

src = sys.argv[1] if len(sys.argv) > 1 else r"C:\Users\user\Documents\PriveDev\grenade_speeds.txt"
out = (sys.argv[2] if len(sys.argv) > 2 else
       r"c:\Users\user\Documents\Prive\AFortOnlineBeacon\Net\Actors\FortThrowSpeeds.Generated.cs")

rows = []
for line in io.open(src, encoding="utf-8"):
    parts = line.rstrip("\n").split("\t")
    if len(parts) < 3:
        continue
    rows.append((parts[0], float(parts[1]), float(parts[2])))

rows.sort(key=lambda r: r[0].lower())

with io.open(out, "w", encoding="utf-8-sig", newline="\r\n") as f:
    w = f.write
    w("// <auto-generated> Tools/ProjectileTable/gen_throw_speeds.py from `pakreader grenadespeeds`"
      " - do not edit by hand. </auto-generated>\n")
    w("//\n")
    w("// How fast each throw ability actually throws, for the %d abilities that override the family's\n" % len(rows))
    w("// 4000. Everything absent from this table inherits that number - a cooked Blueprint stores only\n")
    w("// what it changes, so silence here IS the answer rather than a gap.\n")
    w("//\n")
    w("// Min and Max are both kept because the real ability interpolates between them by throw pitch\n")
    w("// (CalcGrenadeSpeedFromPitch); every one of them happens to set the two equal, which is why one\n")
    w("// number has been enough so far.\n")
    w("\n")
    w("namespace AFortOnlineBeacon.Net.Actors;\n")
    w("\n")
    w("internal static partial class FortThrowSpeeds {\n")
    w("    private static readonly (string Ability, float Min, float Max)[] Rows = {\n")

    for ability, lo, hi in rows:
        w('        ("%s", %gf, %gf),\n' % (ability, lo, hi))

    w("    };\n")
    w("}\n")

print("wrote %d throw speed(s) to %s" % (len(rows), out))
for ability, lo, hi in rows:
    print("  %-48s %g" % (ability, lo))
