namespace AFortOnlineBeacon.Core;

public enum EEngineNetworkVersionHistory : uint {
    HISTORY_INITIAL = 1,
    HISTORY_REPLAY_BACKWARDS_COMPAT = 2,
    HISTORY_MAX_ACTOR_CHANNELS_CUSTOMIZATION = 3,
    HISTORY_REPCMD_CHECKSUM_REMOVE_PRINTF = 4,
    HISTORY_NEW_ACTOR_OVERRIDE_LEVEL = 5,
    HISTORY_CHANNEL_NAMES = 6,
    HISTORY_CHANNEL_CLOSE_REASON = 7,
    HISTORY_ACKS_INCLUDED_IN_HEADER = 8,
    HISTORY_NETEXPORT_SERIALIZATION = 9,
    HISTORY_NETEXPORT_SERIALIZE_FIX = 10,
    HISTORY_FAST_ARRAY_DELTA_STRUCT = 11,
    HISTORY_FIX_ENUM_SERIALIZATION = 12,
    HISTORY_OPTIONALLY_QUANTIZE_SPAWN_INFO = 13,
    HISTORY_JITTER_IN_HEADER = 14,
    HISTORY_CLASSNETCACHE_FULLNAME = 15,
    HISTORY_REPLAY_DORMANCY = 16,

    HISTORY_ENGINENETVERSION_PLUS_ONE,
    HISTORY_ENGINENETVERSION_LATEST = HISTORY_ENGINENETVERSION_PLUS_ONE - 1,
}