#!/usr/bin/env python
"""Turn each item definition's own MaxStackSize into a C# table the inventory can stack against.

WHY THIS EXISTS. The server was adding a new inventory ROW for every pickup, so two boxes of light
ammo sat in two slots instead of one stack of 60 - and the fix needs a per-item number, because
"stack them" is only right for some items. A weapon must never merge into another weapon, rockets cap
at 12 while bullets cap at 999, and those numbers are properties of the assets, not conventions:

    AthenaAmmoDataBulletsLight  999      Athena_Grenade      10      Athena_Bandage   15
    AthenaAmmoDataShells        999      Athena_StickyGrenade 6      AmmoDataRockets  12
    WoodItemData                999      Athena_KnockGrenade  9      MountedTurret    50

Same shape as Tools/HarvestTable and Tools/LootTable: pakreader dumps, this emits, the server compiles
the answer in. See PriveDev/docs/PORTING-TO-ANOTHER-VERSION.md.

ONE ROW OR MANY is the other half of the rule, and MaxStackSize does not carry it: ammo and resources
occupy exactly ONE inventory row however much you hold - harvesting past 999 wood drops the excess on
the ground rather than opening a second wood stack - while a throwable can legitimately sit in two
slots. The item's CLASS is what says which: FortAmmoItemDefinition and FortResourceItemDefinition are
the single-row ones, and grenades are FortWeaponRangedItemDefinition like every other weapon.

INPUT - one `path<TAB>MaxStackSize<TAB>Class` per line, from Tools/PakReader (which needs
FORTNITE_PAKS and FORTNITE_AES_KEY):

    pakreader stacks <fileOfObjectPaths> > stacks.txt

The path list is every item definition the server can ever hold: grep the "/Game/..." strings out of
AFortOnlineBeacon's own sources and generated tables. Anything the list misses simply defaults to
"does not stack", which is the safe answer rather than a wrong one.

    python gen_stacks.py <stacks.txt> <output.cs>
"""
import sys

# ONLY REAL STACKS ARE EMITTED. A size of 0 means the asset does not set the property at all (an
# ability blueprint, a weapon), and 1 means it sets it to "one per slot" - both are the default the
# server already applies, so writing them out would triple the table to say nothing.
MIN_INTERESTING = 2

# Item classes that occupy ONE row no matter how much is held. Everything else may open another.
SINGLE_ROW_CLASSES = {'FortAmmoItemDefinition', 'FortResourceItemDefinition'}


def main():
    if len(sys.argv) < 3:
        print(__doc__)
        return 2

    rows = []
    for line in open(sys.argv[1], encoding='utf-8'):
        parts = line.rstrip('\n').split('\t')
        if len(parts) < 2:
            continue
        try:
            size = int(parts[1])
        except ValueError:
            continue
        klass = parts[2] if len(parts) > 2 else ''
        if size >= MIN_INTERESTING:
            rows.append((parts[0], size, klass in SINGLE_ROW_CLASSES))

    rows.sort()

    with open(sys.argv[2], 'w', encoding='utf-8') as out:
        out.write('// <auto-generated> Tools/StackSizes/gen_stacks.py - do not edit by hand.\n')
        out.write('//\n')
        out.write("// Every item definition's own MaxStackSize, read out of the shipped 10.40 paks. Items that do\n")
        out.write('// not stack are ABSENT rather than listed as 1 - see FortItemStacks.MaxStack for why the\n')
        out.write('// default has to be "one per slot" and not "unlimited". SingleRow marks the items that never\n')
        out.write('// open a second stack (ammo and resources); their overflow goes on the ground instead.\n')
        out.write('\n')
        out.write('namespace AFortOnlineBeacon.Net.Actors;\n\n')
        out.write('internal static partial class FortItemStacks {\n')
        out.write(f'    /// <summary>{len(rows)} stackable item definitions, by object path.</summary>\n')
        out.write('    private static readonly Dictionary<string, (int Max, bool SingleRow)> Sizes =\n')
        out.write('        new(StringComparer.OrdinalIgnoreCase) {\n')
        for path, size, single in rows:
            out.write(f'            ["{path}"] = ({size}, {"true" if single else "false"}),\n')
        out.write('        };\n')
        out.write('}\n')

    print(f'{len(rows)} stackable item definition(s) -> {sys.argv[2]}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
