"""Bake every placed building wall's WORLD transform into FortDoorPlacements.Generated.cs.

    pakreader doors > door_placements.txt          (see PakReader's Doors command)
    python gen_doors.py door_placements.txt

WHY. A door opens AWAY from whoever opened it, and that is a question about SIDES - which side of the
door's own plane the player stands on. This server never loaded the map: an interaction arrives as an
actor PATH and nothing else, so without a table it knows the door's name and not one thing about
where it is or which way it faces, and every door can only swing the same way. That is exactly the
reported symptom.

THE SAME NAME APPEARS MANY TIMES, and that is not a duplicate to be removed. One sublevel - a house
kit - is placed at dozens of POIs, so `Rural_House_Wall_1` is 14 different doors on 14 different
houses. The client names the RUNTIME-duplicated copy (`/Temp/.../Athena_SUB_3x3_House_g2_2384084a`)
whose suffix is generated when the level streams in and cannot be baked, so the right row is chosen
at runtime by proximity to the player who touched the door. Copies of one kit sit hundreds of metres
apart and the player is within arm's reach of the door they opened, so that is never a close call -
see FortDoorPlacements.Nearest.
"""
import io
import sys
from collections import defaultdict

src = sys.argv[1] if len(sys.argv) > 1 else r"C:\Users\user\Documents\PriveDev\door_placements.txt"
out = (sys.argv[2] if len(sys.argv) > 2 else
       r"c:\Users\user\Documents\Prive\AFortOnlineBeacon\Net\Actors\FortDoorPlacements.Generated.cs")

rows = defaultdict(list)
mirrored_count = 0
for line in io.open(src, encoding="utf-8"):
    parts = line.rstrip("\n").split("\t")
    if len(parts) < 4:
        continue
    name, xyz, yaw = parts[0], parts[1].split(","), parts[2]

    # MIRRORED = the placement's 2D scale has a NEGATIVE DETERMINANT. A wall placed with scale.X = -1
    # (2571 of them) or scale.Y = -1 (91) is handed the other way round, so its hinge sits on the
    # opposite side and a swing computed from yaw alone comes out backwards. Non-uniform scales like
    # 1,0.4,1 are just squashed walls and change no handedness, which is why this is a determinant
    # test and not "is any axis negative".
    scale = parts[4].split(",") if len(parts) > 4 else ["1", "1", "1"]
    mirrored = float(scale[0]) * float(scale[1]) < 0
    mirrored_count += 1 if mirrored else 0

    rows[name].append((float(xyz[0]), float(xyz[1]), float(xyz[2]), float(yaw), mirrored))

total = sum(len(v) for v in rows.values())
repeated = sum(1 for v in rows.values() if len(v) > 1)

with io.open(out, "w", encoding="utf-8-sig", newline="\r\n") as f:
    w = f.write
    w("// <auto-generated> Tools/Doors/gen_doors.py from `pakreader doors` - do not edit by hand. </auto-generated>\n")
    w("//\n")
    w("// Every placed building wall on the Athena map in WORLD space, with the yaw it was placed at:\n")
    w("// %d placements under %d distinct actor names, %d of which are placed more than once.\n" % (total, len(rows), repeated))
    w("//\n")
    w("// Positions come from the FOUNDATION WALK, not from reading the sublevels directly - a sublevel\n")
    w("// stores its actors in local space and is placed somewhere else entirely, so a world position only\n")
    w("// exists once the foundation transforms are composed. See PakReader's Doors and WalkLevel.\n")
    w("//\n")
    w("// A repeated name is a real repeat: one house kit placed at many POIs. The row to use is picked by\n")
    w("// proximity at runtime - see FortDoorPlacements.Nearest.\n")
    w("//\n")
    w("// %d of the placements are MIRRORED (a negative 2D scale determinant). That is ~13%% of every wall\n" % mirrored_count)
    w("// on the map, and it is the difference between a door that opens away from you and one that does\n")
    w("// not - see FortDoorPlacements.SideOf.\n")
    w("\n")
    w("namespace AFortOnlineBeacon.Net.Actors;\n")
    w("\n")
    w("internal static partial class FortDoorPlacements {\n")
    w("    /// <summary>\n")
    w("    ///     Actor name, world X/Y/Z, the world yaw the wall faces, and whether the placement is\n")
    w("    ///     MIRRORED - handed the other way round, so its door swings the other way. Sorted by name.\n")
    w("    /// </summary>\n")
    w("    private static readonly (string Name, float X, float Y, float Z, float Yaw, bool Mirrored)[] Placements = {\n")

    for name in sorted(rows, key=str.lower):
        for x, y, z, yaw, mirrored in rows[name]:
            w('        ("%s", %gf, %gf, %gf, %gf, %s),\n' % (name, x, y, z, yaw, "true" if mirrored else "false"))

    w("    };\n")
    w("}\n")

print("wrote %d placement(s) for %d name(s) to %s" % (total, len(rows), out))
