"""Bake the building-wall NAME gate into FortMapWalls.Generated.cs.

    pakreader walls > map_walls.txt
    python gen_walls.py map_walls.txt

The other half of the same bake: gen_doors.py turns `pakreader doors` into the WORLD TRANSFORMS a
door needs to open the right way, and this turns `pakreader walls` into the NAME GATE that decides
whether an actor may be treated as a wall at all. Both use the same class test in PakReader
(`IsWallFolder`), and they have to: a name this gate admits but the transform table has never heard
of opens at a fixed angle, and a name the gate refuses can never be opened at all.

WHY THE GATE EXISTS. An interaction arrives as a client-supplied actor PATH, and acting on it means
pushing WALL HANDLES at a stand-in. If the actor's real class is not a wall, that is a handle the
class does not have and the client DROPS THE CONNECTION. So the question is "is it safe to send wall
properties to this actor", and nothing else - see the generated file's own header.
"""
import io
import sys

src = sys.argv[1] if len(sys.argv) > 1 else r"C:\Users\user\Documents\PriveDev\map_walls.txt"
out = (sys.argv[2] if len(sys.argv) > 2 else
       r"c:\Users\user\Documents\Prive\AFortOnlineBeacon\Net\Actors\FortMapWalls.Generated.cs")

names = {}
for line in io.open(src, encoding="utf-8"):
    parts = line.rstrip("\n").split("\t")
    if len(parts) >= 2:
        names[parts[0]] = parts[1]

with io.open(out, "w", encoding="utf-8-sig", newline="\r\n") as f:
    w = f.write
    w("// <auto-generated> Tools/Doors/gen_walls.py from `pakreader walls` - do not edit by hand. </auto-generated>\n")
    w("//\n")
    w("// Every placed actor on the Athena map whose CLASS is a building wall - %d of them, swept from\n" % len(names))
    w("// all 455 Athena .umap packages. A door is one of these; so is a plain wall.\n")
    w("//\n")
    w("// WHAT THIS GATE IS FOR. An interaction arrives as a client-supplied actor PATH, and acting on it\n")
    w("// means building an ABuildingWall stand-in and pushing WALL HANDLES at it. If the actor's real class\n")
    w("// is not a wall, that is a handle the class does not have, and the client DROPS THE CONNECTION -\n")
    w("// which is exactly what `Prop_Athena_Doorbell_Interactable_2` did (its class is\n")
    w("// `BuildingPropSimpleInteract`). So the question this table answers is \"is it safe to send wall\n")
    w("// properties to this actor\", and nothing else.\n")
    w("//\n")
    w("// IT DOES NOT ASK WHETHER THE ACTOR HAS A DOOR. An earlier version did, by requiring \"Door\" in the\n")
    w("// class name, and that excluded `Rural_House_Wall_9_C` - a `Parent_BuildingWall_C` subclass with a\n")
    w("// door in it - so that door could never be opened. Whether a wall has a door is the client's\n")
    w("// business: it owns the mesh and the prompt, and OnRep_bDoorOpen on a wall without one does nothing.\n")
    w("//\n")
    w("// The gate is the class ASSET's location: under Building/ActorBlueprints, in a folder named Wall or\n")
    w("// WALLS. The plural cost 2,923 actors and every themed POI's doors - PirateShip, IceCastle,\n")
    w("// ArcticBase, WinterVillage, Neo - because the first test was a `/Wall/` substring, and \"/Walls/\"\n")
    w("// does not contain \"/Wall/\". The symptom was a door the client offered to open, predicted the swing\n")
    w("// for, and could then never close, because the server never agreed it existed.\n")
    w("\n")
    w("namespace AFortOnlineBeacon.Net.Actors;\n")
    w("\n")
    w("internal static class FortMapWalls {\n")
    w("    /// <summary>Actor names (the leaf of the path the client sends) whose class is a real building wall.</summary>\n")
    w("    private static readonly HashSet<string> Names = new(StringComparer.OrdinalIgnoreCase) {\n")

    for name in sorted(names, key=str.lower):
        w('        "%s",\n' % name)

    w("    };\n")
    w("\n")
    w("    /// <summary>Whether the leaf of a client-supplied actor path is a class-verified building wall.</summary>\n")
    w("    public static bool IsBuildingWall(string actorPath) =>\n")
    w("        Names.Contains(actorPath[(actorPath.LastIndexOf('.') + 1)..]);\n")
    w("}\n")

print("wrote %d wall actor name(s) to %s" % (len(names), out))
