#!/usr/bin/env python
"""Emit FortWeaponNetCaches' tables for every AFortWeapon subclass in the Dumper-7 SDK.

Why this needs its own generator instead of gen_net_fields.py: a weapon's real class is chosen per
item (see FortWeaponActorClasses), so there is no ONE chain to hand-transcribe the way there is for
the PlayerController or the GameState. FClassNetCache's FieldNetIndex bit WIDTH comes from the total
own+inherited field count of that exact class, so B_Assault_Auto_Athena_C (38 fields) and
B_Athena_Pickaxe_Generic_C (32) do not even agree on how many bits a field index takes.

REQUIRES AN IN-MATCH DUMP. A Blueprint class that is not loaded is not in the SDK at all, and a
lobby dump has none of the weapon Blueprints in it - B_Athena_Pickaxe_Generic_C was simply absent
from the 2026-08-26 dump, which is why this table could not be built before 2026-08-27. Anything
still missing falls back to the bare AFortWeapon chain at runtime, which is only correct for a class
that adds nothing of its own.

Same extraction rule as everywhere else: a class's OWN net fields are its CPF_Net properties plus
its FUNC_Net functions, sorted by name (ordinal, case-insensitive), assigned base-first.

Usage:
    python Tools/NetFieldVerify/gen_weapon_net_fields.py \
        > AFortOnlineBeacon/Net/FortWeaponNetCaches.Generated.cs
"""
import glob
import os
import re
import sys

SDK = r"C:/Dumper-7/4.23.0-9380822+++Fortnite+Release-10.40-FortniteGame/CppSDK/SDK"

CLASS_RE = re.compile(r"^class\s+(?:\w+\([^)]*\)\s+)?(\w+)(?:\s+final)?\s*:\s*public\s+(\w+)", re.M)
PROP_RE = re.compile(
    r"\s(\w+)\s*(?:\[\s*0x[0-9A-Fa-f]+\s*\])?\s*(?::\s*1\s*)?;"
    r"\s*//\s*0x[0-9A-Fa-f]+\(0x[0-9A-Fa-f]+\)\((.*)\)\s*$")
NET_RE = re.compile(r"(?<![A-Za-z0-9_])Net(?![A-Za-z0-9_])")

_files = {}


def read(name):
    if name not in _files:
        path = os.path.join(SDK, name)
        _files[name] = open(path, encoding="utf-8", errors="replace").read() if os.path.isfile(path) else ""
    return _files[name]


def build_index():
    """class name -> (super, package). Dumper-7 splits Blueprints into per-package files and marks
    them "// BlueprintGeneratedClass Pkg.Cls" rather than "// Class Pkg.Cls"."""
    supers, package = {}, {}
    for path in glob.glob(os.path.join(SDK, "*_classes.hpp")):
        text = read(os.path.basename(path))
        for m in CLASS_RE.finditer(text):
            supers.setdefault(m.group(1), m.group(2))
        for m in re.finditer(r"^// (?:Class|BlueprintGeneratedClass) ([\w/.]+)\.(\w+)$", text, re.M):
            package.setdefault("A" + m.group(2), (m.group(1), os.path.basename(path)[:-len("_classes.hpp")]))
    return supers, package


def own_fields(pkg, cls, prefix):
    funcs = []
    lines = read(prefix + "_functions.cpp").split("\n")
    pat = re.compile(r"// Function %s\.%s\.(\w+)$" % (re.escape(pkg), re.escape(cls)))
    for i, line in enumerate(lines):
        m = pat.match(line.strip())
        if m and i + 1 < len(lines):
            flags = lines[i + 1].strip()
            if flags.startswith("// (") and NET_RE.search(flags):
                funcs.append(m.group(1))

    hpp = read(prefix + "_classes.hpp")
    props = []
    for marker in ("// BlueprintGeneratedClass %s.%s\n" % (pkg, cls), "// Class %s.%s\n" % (pkg, cls)):
        start = hpp.find(marker)
        if start == -1:
            continue
        body = hpp[start:hpp.index("\n};", start)]
        for line in body.split("\n"):
            m = PROP_RE.search(line)
            if m and NET_RE.search(m.group(2)) and not m.group(1).startswith(("Pad_", "BitPad_")):
                props.append(m.group(1))
        break

    return sorted(set(props) | set(funcs), key=str.lower)


def main():
    supers, package = build_index()

    def chain(cls):
        """AFortWeapon-first list of class names down to cls, or None if cls is not a weapon."""
        out = []
        seen = set()
        c = cls
        while c in supers and c not in seen:
            out.append(c)
            seen.add(c)
            if c == "AFortWeapon":
                return list(reversed(out))
            c = supers[c]
        return None

    chains, fields = {}, {}
    for cls in supers:
        c = chain(cls)
        if c is None:
            continue
        chains[cls] = c
        for link in c:
            if link in fields or link not in package:
                continue
            pkg, prefix = package[link]
            fields[link] = own_fields(pkg, link[1:], prefix)

    def cs_array(names):
        return "new[] { " + ", ".join('"%s"' % n for n in names) + " }" if names else "Array.Empty<string>()"

    print('''// GENERATED by Tools/NetFieldVerify/gen_weapon_net_fields.py from an IN-MATCH Dumper-7 dump.
// Do not edit by hand. See the script's docstring for why an in-match dump is required.

namespace AFortOnlineBeacon.Net;

internal static partial class FortWeaponNetCaches {
    /// <summary>Each class's OWN net fields (CPF_Net properties + FUNC_Net functions), name-sorted. %d classes.</summary>
    private static readonly Dictionary<string, string[]> OwnFields = new(StringComparer.Ordinal) {''' % len(fields))
    for name in sorted(fields, key=str.lower):
        print('        ["%s"] = %s,' % (name[1:], cs_array(fields[name])))
    print("    };")
    print()
    print('''    /// <summary>Weapon class name -> its chain from AFortWeapon down, base first. %d classes.</summary>
    private static readonly Dictionary<string, string[]> Chains = new(StringComparer.Ordinal) {''' % len(chains))
    for name in sorted(chains, key=str.lower):
        print('        ["%s"] = %s,' % (name[1:], cs_array(n[1:] for n in chains[name])))
    print("    };")
    print("}")


main()
